// Pixel-art sprites: string maps rendered as SVG rects (crispEdges).
// Chars: '.' transparent; everything else looked up in the sprite's palette.

// The mascot: a white call duck, side profile facing right.
// W body, w shading, K eye, O bill/feet, o bill shadow
// B/b pond water + ripples, S/s laptop screen + code, G/g laptop body, D thought dots
export const DUCK = {
  palette: {
    W: '#f2f0ec', w: '#c9c5bc', K: '#1c1c20', O: '#e0913c', o: '#b06f2c',
    B: '#4f6d7d', b: '#7a99ab', S: '#2f3e35', s: '#9ec489', G: '#55534f', g: '#7a7671', D: '#9c9a96',
    // thinking cap: C cap, T tassel — search: M glass rim, L lens —
    // image: E easel/canvas, H paint dab, P shared prop handle — quack: Q sound burst
    C: '#3a3a5c', T: '#d9a05b', M: '#c9c5bc', L: '#bfe3ec', E: '#e8e6e2', H: '#c96a5b', P: '#8a5a34', Q: '#9c9a96',
    N: '#c9a468',
  },
  idle: [
    '................',
    '.........WWWW...',
    '........WWWWWW..',
    '........WWWKWW..',
    '........WWWWWWOO',
    '........WWWWWoO.',
    '.........WWWW...',
    '.........WWWW...',
    'WW.....WWWWWW...',
    'WW...WWWWWWWW...',
    'WWWWWWWWWWWWW...',
    '.WWWWWWWWWWWW...',
    '..WWWWWWWWWWw...',
    '....WWWWWWWw....',
    '.....O...O......',
    '................',
  ],
  // paddling in the pond — two frames, ripples drift
  swim1: [
    '................',
    '................',
    '.........WWWW...',
    '........WWWWWW..',
    '........WWWKWW..',
    '........WWWWWWOO',
    '........WWWWWoO.',
    '.........WWWW...',
    'WW.....WWWWWW...',
    'WW...WWWWWWWW...',
    'WWWWWWWWWWWWW...',
    'BBBBBBBBBBBBBBBB',
    '.bb...BB....bb..',
    '....bb....BB....',
    '................',
    '................',
  ],
  swim2: [
    '................',
    '................',
    '.........WWWW...',
    '........WWWWWW..',
    '........WWWwWW..',
    '........WWWWWWOO',
    '........WWWWWoO.',
    '.........WWWW...',
    'WW.....WWWWWW...',
    'WW...WWWWWWWW...',
    'WWWWWWWWWWWWW...',
    'BBBBBBBBBBBBBBBB',
    '...BB....bb...BB',
    '.bb....BB....bb.',
    '................',
    '................',
  ],
  // dabbling — tail up, head underwater, feet kicking
  dive1: [
    '................',
    '................',
    '................',
    '................',
    '................',
    '......O..O......',
    '.......WW.......',
    '......WWWW......',
    '......WWWW......',
    '.....WWWWWW.....',
    '....WWWWWWWW....',
    'BBBBBBBBBBBBBBBB',
    '.bb..BBBB...bb..',
    '....bb....BB....',
    '................',
    '................',
  ],
  dive2: [
    '................',
    '................',
    '................',
    '................',
    '................',
    '.....O..O.......',
    '........WW......',
    '......WWWW......',
    '.....WWWWW......',
    '.....WWWWWW.....',
    '....WWWWWWWW....',
    'BBBBBBBBBBBBBBBB',
    '...BB....bb...BB',
    '.bb....BB....bb.',
    '................',
    '................',
  ],
  // hammering on a tiny laptop — screen glyphs flicker, wing taps
  code1: [
    '..................',
    '.........WWWW.....',
    '........WWWWWW....',
    '........WWWKWW....',
    '........WWWWWWOO..',
    '........WWWWWoO...',
    '.........WWWW..SSS',
    '.........WWWW..SsS',
    'WW.....WWWWWW..SSS',
    'WW...WWWWWWWW..SsS',
    'WWWWWWWWWWWWW..SSS',
    '.WWWWWWWWWWWWGGGGG',
    '..WWWWWWWWWWwGgGGG',
    '....WWWWWWWw......',
    '.....O...O........',
    '..................',
  ],
  code2: [
    '..................',
    '.........WWWW.....',
    '........WWWWWW....',
    '........WWWKWW....',
    '........WWWWWWOO..',
    '........WWWWWoO...',
    '.........WWWW..SSS',
    '.........WWWW..SSs',
    'WW.....WWWWWW..SsS',
    'WW...WWWWWWWW..SSS',
    'WWWWWWWWWWWWW..sSS',
    '.WWWWWWWWWWWWGGGGG',
    '..WWWWWWWWWWwGGGgG',
    '....WWWWWWWw......',
    '.....O...O........',
    '..................',
  ],
  // pondering — thought dots rise
  think1: [
    '..............D.',
    '................',
    '.........WWWW...',
    '........WWWWWW..',
    '........WWWKWW..',
    '........WWWWWWOO',
    '........WWWWWoO.',
    '.........WWWW...',
    'WW.....WWWWWW...',
    'WW...WWWWWWWW...',
    'WWWWWWWWWWWWW...',
    '.WWWWWWWWWWWW...',
    '..WWWWWWWWWWw...',
    '....WWWWWWWw....',
    '.....O...O......',
    '................',
  ],
  think2: [
    '...........D....',
    '.............DD.',
    '.........WWWW...',
    '........WWWWWW..',
    '........WWWKWW..',
    '........WWWWWWOO',
    '........WWWWWoO.',
    '.........WWWW...',
    'WW.....WWWWWW...',
    'WW...WWWWWWWW...',
    'WWWWWWWWWWWWW...',
    '.WWWWWWWWWWWW...',
    '..WWWWWWWWWWw...',
    '....WWWWWWWw....',
    '.....O...O......',
    '................',
  ],
  // eyes-closed frame for blinking
  blink: [
    '................',
    '.........WWWW...',
    '........WWWWWW..',
    '........WWWwWW..',
    '........WWWWWWOO',
    '........WWWWWoO.',
    '.........WWWW...',
    '.........WWWW...',
    'WW.....WWWWWW...',
    'WW...WWWWWWWW...',
    'WWWWWWWWWWWWW...',
    '.WWWWWWWWWWWW...',
    '..WWWWWWWWWWw...',
    '....WWWWWWWw....',
    '.....O...O......',
    '................',
  ],
  error1: [
    '............D...',
    '.........WWWW...',
    '........WWWWWW..',
    '........WWWwWW..',
    '........WWWWWWOO',
    '........WWWWWBO.',
    '.........WWWW...',
    '.........WWWW...',
    'WW.....WWWWWW...',
    'WW...WWWWWWWW...',
    'WWWWWWWWWWWWW...',
    '.WWWWWWWWWWWW...',
    '..WWWWWWWWWWw...',
    '....WWWWWWWw....',
    '.....O...O......',
    '................',
  ],
  error2: [
    '...........D.D..',
    '.........WWWW...',
    '........WWWWWW..',
    '........WWWwWW..',
    '........WWWWWWOO',
    '........WWWWWoO.',
    '.........WWWWB..',
    '.........WWWW...',
    'WW.....WWWWWW...',
    'WW...WWWWWWWW...',
    'WWWWWWWWWWWWW...',
    '.WWWWWWWWWWWW...',
    '..WWWWWWWWWWw...',
    '....WWWWWWWw....',
    '.....O...O......',
    '................',
  ],
  confused1: [
    '................',
    '.........WWWW.D.',
    '........WWWWWW..',
    '........WWWWWW..',
    '........WWWWKWOO',
    '........WWWWWoO.',
    '.........WWWW...',
    '.........WWWW...',
    'WW.....WWWWWW...',
    'WW...WWWWWWWW...',
    'WWWWWWWWWWWWW...',
    '.WWWWWWWWWWWW...',
    '..WWWWWWWWWWw...',
    '....WWWWWWWw....',
    '.....O...O......',
    '................',
  ],
  confused2: [
    '.............D..',
    '.........WWWW...',
    '........WWWWWW..',
    '........WWWWWW..',
    '........WWWWKWOO',
    '........WWWWWoO.',
    '.........WWWW...',
    '.........WWWW...',
    'WW.....WWWWWW...',
    'WW...WWWWWWWW...',
    'WWWWWWWWWWWWW...',
    '.WWWWWWWWWWWW...',
    '..WWWWWWWWWWw...',
    '....WWWWWWWw....',
    '.....O...O......',
    '................',
  ],
  sleep1: [
    '................',
    '.........WWWWD..',
    '........WWWWWW..',
    '........WWWwWW..',
    '........WWWWWWOO',
    '........WWWWWoO.',
    '.........WWWW...',
    '.........WWWW...',
    'WW.....WWWWWW...',
    'WW...WWWWWWWW...',
    'WWWWWWWWWWWWW...',
    '.WWWWWWWWWWWW...',
    '..WWWWWWWWWWw...',
    '....WWWWWWWw....',
    '.....O...O......',
    '................',
  ],
  sleep2: [
    '..............D.',
    '.........WWWD...',
    '........WWWWWW..',
    '........WWWwWW..',
    '........WWWWWWOO',
    '........WWWWWoO.',
    '.........WWWW...',
    '.........WWWW...',
    'WW.....WWWWWW...',
    'WW...WWWWWWWW...',
    'WWWWWWWWWWWWW...',
    '.WWWWWWWWWWWW...',
    '..WWWWWWWWWWw...',
    '....WWWWWWWw....',
    '.....O...O......',
    '................',
  ],
  wave1: [
    '................',
    '.........WWWW...',
    '........WWWWWW..',
    '........WWWKWW..',
    '........WWWWWWOO',
    'W.......WWWWWoO.',
    'W........WWWW...',
    '.W.......WWWW...',
    'WW.....WWWWWW...',
    'WW...WWWWWWWW...',
    'WWWWWWWWWWWWW...',
    '.WWWWWWWWWWWW...',
    '..WWWWWWWWWWw...',
    '....WWWWWWWw....',
    '.....O...O......',
    '................',
  ],
  wave2: [
    '................',
    '.........WWWW...',
    '........WWWWWW..',
    '........WWWKWW..',
    '.W......WWWWWWOO',
    '.W......WWWWWoO.',
    '..W......WWWW...',
    '.........WWWW...',
    'WW.....WWWWWW...',
    'WW...WWWWWWWW...',
    'WWWWWWWWWWWWW...',
    '.WWWWWWWWWWWW...',
    '..WWWWWWWWWWw...',
    '....WWWWWWWw....',
    '.....O...O......',
    '................',
  ],
  nom1: [
    '................',
    '.........WWWW...',
    '........WWWWWW..',
    '........WWWKWW..',
    '........WWWWWWOO',
    '........WWWWWoON',
    '.........WWWW...',
    '.........WWWW...',
    'WW.....WWWWWW...',
    'WW...WWWWWWWW...',
    'WWWWWWWWWWWWW...',
    '.WWWWWWWWWWWW...',
    '..WWWWWWWWWWw...',
    '....WWWWWWWw....',
    '.....O...O......',
    '................',
  ],
  nom2: [
    '................',
    '.........WWWW...',
    '........WWWWWW..',
    '........WWWKWW..',
    '........WWWWWWON',
    '........WWWWWoO.',
    '.........WWWW..D',
    '.........WWWW...',
    'WW.....WWWWWW...',
    'WW...WWWWWWWW...',
    'WWWWWWWWWWWWW...',
    '.WWWWWWWWWWWW...',
    '..WWWWWWWWWWw...',
    '....WWWWWWWw....',
    '.....O...O......',
    '................',
  ],
  // thinking REALLY hard — mortarboard on, tassel swings side to side
  thinkcap1: [
    '........CCCCCCT.',
    '.........WWWW...',
    '........WWWWWW..',
    '........WWWKWW..',
    '........WWWWWWOO',
    '........WWWWWoO.',
    '.........WWWW...',
    '.........WWWW...',
    'WW.....WWWWWW...',
    'WW...WWWWWWWW...',
    'WWWWWWWWWWWWW...',
    '.WWWWWWWWWWWW...',
    '..WWWWWWWWWWw...',
    '....WWWWWWWw....',
    '.....O...O......',
    '................',
  ],
  thinkcap2: [
    '.......TCCCCCC..',
    '.........WWWW...',
    '........WWWWWW..',
    '........WWWKWW..',
    '........WWWWWWOO',
    '........WWWWWoO.',
    '.........WWWW...',
    '.........WWWW...',
    'WW.....WWWWWW...',
    'WW...WWWWWWWW...',
    'WWWWWWWWWWWWW...',
    '.WWWWWWWWWWWW...',
    '..WWWWWWWWWWw...',
    '....WWWWWWWw....',
    '.....O...O......',
    '................',
  ],
  // web searching — magnifying glass up front, lens glint alternates
  search1: [
    '................',
    '..MMM....WWWW...',
    '..MLM...WWWWWW..',
    '..MMM...WWWKWW..',
    '.P......WWWWWWOO',
    'P.......WWWWWoO.',
    '.........WWWW...',
    '.........WWWW...',
    'WW.....WWWWWW...',
    'WW...WWWWWWWW...',
    'WWWWWWWWWWWWW...',
    '.WWWWWWWWWWWW...',
    '..WWWWWWWWWWw...',
    '....WWWWWWWw....',
    '.....O...O......',
    '................',
  ],
  search2: [
    '................',
    '..MMM....WWWW...',
    '..MML...WWWWWW..',
    '..MMM...WWWKWW..',
    '..P.....WWWWWWOO',
    '.P......WWWWWoO.',
    '.........WWWW...',
    '.........WWWW...',
    'WW.....WWWWWW...',
    'WW...WWWWWWWW...',
    'WWWWWWWWWWWWW...',
    '.WWWWWWWWWWWW...',
    '..WWWWWWWWWWw...',
    '....WWWWWWWw....',
    '.....O...O......',
    '................',
  ],
  // generating an image — tiny easel + canvas, paint dabs swap (brush stroke)
  image1: [
    '................',
    '.EEEE....WWWW...',
    '.EHWE...WWWWWW..',
    '.EWHE...WWWKWW..',
    '.EEEE...WWWWWWOO',
    '..P.....WWWWWoO.',
    '.P.......WWWW...',
    '.........WWWW...',
    'WW.....WWWWWW...',
    'WW...WWWWWWWW...',
    'WWWWWWWWWWWWW...',
    '.WWWWWWWWWWWW...',
    '..WWWWWWWWWWw...',
    '....WWWWWWWw....',
    '.....O...O......',
    '................',
  ],
  image2: [
    '................',
    '.EEEE....WWWW...',
    '.EWHE...WWWWWW..',
    '.EHWE...WWWKWW..',
    '.EEEE...WWWWWWOO',
    '...P....WWWWWoO.',
    '..P......WWWW...',
    '.........WWWW...',
    'WW.....WWWWWW...',
    'WW...WWWWWWWW...',
    'WWWWWWWWWWWWW...',
    '.WWWWWWWWWWWW...',
    '..WWWWWWWWWWw...',
    '....WWWWWWWw....',
    '.....O...O......',
    '................',
  ],
  // idle filler: stretches a wing up
  stretch1: [
    '................',
    '.........WWWW...',
    '........WWWWWW..',
    '........WWWKWW..',
    '........WWWWWWOO',
    'W.......WWWWWoO.',
    'W........WWWW...',
    'W........WWWW...',
    'WW.....WWWWWW...',
    'WW...WWWWWWWW...',
    'WWWWWWWWWWWWW...',
    '.WWWWWWWWWWWW...',
    '..WWWWWWWWWWw...',
    '....WWWWWWWw....',
    '.....O...O......',
    '................',
  ],
  stretch2: [
    '................',
    '.........WWWW...',
    '........WWWWWW..',
    '........WWWKWW..',
    '........WWWWWWOO',
    '.W......WWWWWoO.',
    '.W.......WWWW...',
    'WW.......WWWW...',
    'WW.....WWWWWW...',
    'WW...WWWWWWWW...',
    'WWWWWWWWWWWWW...',
    '.WWWWWWWWWWWW...',
    '..WWWWWWWWWWw...',
    '....WWWWWWWw....',
    '.....O...O......',
    '................',
  ],
  // idle filler: head dips down to peck/preen, tail flicks
  preen1: [
    '................',
    '.........WWWW...',
    '........WWWWWW..',
    '........WWWWWW..',
    '........WWWKWWOO',
    '........WWWWWoO.',
    '.........WWWW...',
    '.........WWWW...',
    'WW.....WWWWWW...',
    'WW...WWWWWWWW...',
    'WWWWWWWWWWWWW...',
    '.WWWWWWWWWWWW...',
    '..WWWWWWWWWWW...',
    '....WWWWWWWww...',
    '.....O...O......',
    '................',
  ],
  preen2: [
    '................',
    '.........WWWW...',
    '........WWWWWW..',
    '........WWWWWW..',
    '........WWWKWWOO',
    '........WWWWWoO.',
    '.........WWWW...',
    '.........WWWW...',
    'WW.....WWWWWW...',
    'WW...WWWWWWWW...',
    'WWWWWWWWWWWWW...',
    '.WWWWWWWWWWWW...',
    '..WWWWWWWWWWww..',
    '....WWWWWWWw....',
    '.....O...O......',
    '................',
  ],
  // talking — mouth cracks open mid-word, alternates with the plain idle frame
  talk2: [
    '................',
    '.........WWWW...',
    '........WWWWWW..',
    '........WWWKWW..',
    '........WWWWWWOO',
    '........WWWWWo..',
    '.........WWWW..D',
    '.........WWWW...',
    'WW.....WWWWWW...',
    'WW...WWWWWWWW...',
    'WWWWWWWWWWWWW...',
    '.WWWWWWWWWWWW...',
    '..WWWWWWWWWWw...',
    '....WWWWWWWw....',
    '.....O...O......',
    '................',
  ],
  // idle filler: a little quack, sound burst above the bill
  quack1: [
    '.............Q..',
    '.........WWWW...',
    '........WWWWWW..',
    '........WWWKWW..',
    '........WWWWWWOO',
    '........WWWWWoO.',
    '.........WWWW...',
    '.........WWWW...',
    'WW.....WWWWWW...',
    'WW...WWWWWWWW...',
    'WWWWWWWWWWWWW...',
    '.WWWWWWWWWWWW...',
    '..WWWWWWWWWWw...',
    '....WWWWWWWw....',
    '.....O...O......',
    '................',
  ],
  quack2: [
    '.............QQ.',
    '.........WWWW...',
    '........WWWWWW..',
    '........WWWKWW..',
    '........WWWWWWOO',
    '........WWWWWoO.',
    '.........WWWW...',
    '.........WWWW...',
    'WW.....WWWWWW...',
    'WW...WWWWWWWW...',
    'WWWWWWWWWWWWW...',
    '.WWWWWWWWWWWW...',
    '..WWWWWWWWWWw...',
    '....WWWWWWWw....',
    '.....O...O......',
    '................',
  ],
};

const grey = '#9c9a96';
const accent = '#d9a05b';

export const ICONS = {
  // pushpin: head, flange, needle
  pin: {
    palette: { P: grey },
    map: [
      '...PPPP...',
      '...PPPP...',
      '...PPPP...',
      '..PPPPPP..',
      '.PPPPPPPP.',
      '....PP....',
      '....PP....',
      '....P.....',
    ],
  },
  pinOn: {
    palette: { P: accent },
    map: null, // filled below — same shape as pin
  },
  // settings: three sliders with offset knobs
  sliders: {
    palette: { G: '#55534f', K: grey },
    map: [
      '..KKK......',
      'GGKKKGGGGGG',
      '..KKK......',
      '...........',
      '.......KKK.',
      'GGGGGGGKKKG',
      '.......KKK.',
      '...........',
      '...KKK.....',
      'GGGKKKGGGGG',
      '...KKK.....',
    ],
  },
  plus: {
    palette: { P: '#e8e6e2' },
    map: [
      '...PP...',
      '...PP...',
      '...PP...',
      'PPPPPPPP',
      'PPPPPPPP',
      '...PP...',
      '...PP...',
      '...PP...',
    ],
  },
  arrowUp: {
    palette: { P: '#e8e6e2' },
    map: [
      '....P....',
      '...PPP...',
      '..PPPPP..',
      '.PPPPPPP.',
      'PPPPPPPPP',
      '...PPP...',
      '...PPP...',
      '...PPP...',
      '...PPP...',
    ],
  },
  stop: {
    palette: { P: '#c96a5b' },
    map: [
      '.PPPPPP.',
      'PPPPPPPP',
      'PPPPPPPP',
      'PPPPPPPP',
      'PPPPPPPP',
      'PPPPPPPP',
      'PPPPPPPP',
      '.PPPPPP.',
    ],
  },
};
ICONS.pinOn.map = ICONS.pin.map;

// action-row icons (grey; hover color handled in CSS via opacity)
ICONS.pencil = {
  palette: { P: grey },
  map: [
    '......PP.',
    '.....PPPP',
    '....PPPP.',
    '...PPPP..',
    '..PPPP...',
    '.PPPP....',
    'PPP......',
    'P........',
  ],
};
ICONS.trash = {
  palette: { P: grey },
  map: [
    '...PPP...',
    '.PPPPPPP.',
    '..PPPPP..',
    '..P.P.P..',
    '..P.P.P..',
    '..P.P.P..',
    '..PPPPP..',
    '...PPP...',
  ],
};
ICONS.copy = {
  palette: { P: grey },
  map: [
    '...PPPPPP.',
    '...P....P.',
    '...P....P.',
    'PPPPPP..P.',
    'P....P..P.',
    'P....PPPP.',
    'P....P....',
    'P....P....',
    'PPPPPP....',
  ],
};
ICONS.retry = {
  palette: { P: grey },
  map: [
    '...PPPP...',
    '..PP..PP..',
    '.PP....PP.',
    '.P.....PPP',
    '.P......P.',
    '.P.....PP.',
    '.PP....P..',
    '..PP..PP..',
    '...PPPP...',
  ],
};

// Merge horizontal runs of same-colored pixels into single rects.
export function buildRects(map, palette) {
  const rects = [];
  for (let y = 0; y < map.length; y++) {
    const row = map[y];
    let x = 0;
    while (x < row.length) {
      const ch = row[x];
      if (ch === '.' || !palette[ch]) { x++; continue; }
      let end = x + 1;
      while (end < row.length && row[end] === ch) end++;
      rects.push({ x, y, w: end - x, c: palette[ch] });
      x = end;
    }
  }
  return rects;
}

export function toSvg(map, palette, extraAttrs = '') {
  const w = map[0].length;
  const h = map.length;
  const body = buildRects(map, palette)
    .map((r) => `<rect x="${r.x}" y="${r.y}" width="${r.w}" height="1" fill="${r.c}"/>`)
    .join('');
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${w} ${h}" shape-rendering="crispEdges" ${extraAttrs}>${body}</svg>`;
}
