// Pixel-art sprites: string maps rendered as SVG rects (crispEdges).
// Chars: '.' transparent; everything else looked up in the sprite's palette.

// The mascot: a white call duck, side profile facing right. 32x32 base grid
// (code frames are wider, 42x32, to fit a laptop) — round call-duck body,
// layered bill, a cheek blush and sparkle-highlight eye for personality.
// W body, w shading/highlight, K eye, O bill/feet, o bill shadow, P blush
// B/b pond water + ripples, S/s laptop screen + code, G/g laptop body
// D thought dots, C/T thinking cap + tassel, M/L magnifying glass + lens,
// E/H/A easel canvas + paint dab + brush handle, Q quack sound burst
export const DUCK = {
  palette: {
    W: '#f2f0ec', w: '#dcd8d1', K: '#1c1c20', O: '#e0913c', o: '#b06f2c', P: '#f0b8c4',
    B: '#4f6d7d', b: '#7a99ab', S: '#2f3e35', s: '#9ec489', G: '#55534f', g: '#7a7671', D: '#9c9a96',
    C: '#3a3a5c', T: '#d9a05b', M: '#c9c5bc', L: '#bfe3ec', E: '#e8e6e2', H: '#c96a5b', A: '#8a5a34', Q: '#9c9a96',
  },
  idle: [
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '...................WWWWW........',
    '.................WWWWWWWWW......',
    '................WWWWWW.WWWW.....',
    '...............WWWWWWWKKWWWW....',
    '...............WWWWWWWKwWWWW....',
    '..............WWWWWWWWKKWWOOOO..',
    '..............WWWWWWPPWWWWOOOO..',
    '..............WWWWWWWWWWWOOOOO..',
    '..............WWWWWWWWWWWoooO...',
    '..............WWWWWWWWWWWoooW...',
    '..............WWWWWWWWWWWWWWW...',
    '.........WWWWWWWWWWWWWWWWWWWW...',
    '.......WWWWWWWWWwwwwWWWWWWWW....',
    '.....WWWWWWWWWWWWwwwwWWWWWWW....',
    '....WWWWWWWWWWWWWWwwwWWWWWW.....',
    '...WWWWWWwWWWWWWWWwwwwWWWWWW....',
    '...WWWWWWWWWWWWWWWWwwwwWWWWW....',
    '...WWWWWWWwWWWWWWWWwwwwWWWWW....',
    '..WWWWWWWWWWWWWWWWWwwwwWWWWWW...',
    '...WWWWWWWWWWWWWWWWwwwwWWWWW....',
    '...WWWWWWWWwWWWWWWwwwwWWWWWW....',
    '...WWWWWWWWWWWWWWWwwwWwWWWWW....',
    '....WWWWwWWWWWWWWwwwwWWWWWW.....',
    '.....WWWWWWWWWWWwwwwWWWWWW......',
    '.......WWoooWWWWWWWoooWW........',
    '.........OOOWWWWWWWOOO..........',
    '.........OOO...W...OOO..........',
  ],
  blink: [
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '...................WWWWW........',
    '.................WWWWWWWWW......',
    '................WWWWWWWWWWW.....',
    '...............WWWWWWWWWWWWW....',
    '...............WWWWWWwwwWWWW....',
    '..............WWWWWWWWWWWWOOOO..',
    '..............WWWWWWPPWWWWOOOO..',
    '..............WWWWWWWWWWWOOOOO..',
    '..............WWWWWWWWWWWoooO...',
    '..............WWWWWWWWWWWoooW...',
    '..............WWWWWWWWWWWWWWW...',
    '.........WWWWWWWWWWWWWWWWWWWW...',
    '.......WWWWWWWWWwwwwWWWWWWWW....',
    '.....WWWWWWWWWWWWwwwwWWWWWWW....',
    '....WWWWWWWWWWWWWWwwwWWWWWW.....',
    '...WWWWWWwWWWWWWWWwwwwWWWWWW....',
    '...WWWWWWWWWWWWWWWWwwwwWWWWW....',
    '...WWWWWWWwWWWWWWWWwwwwWWWWW....',
    '..WWWWWWWWWWWWWWWWWwwwwWWWWWW...',
    '...WWWWWWWWWWWWWWWWwwwwWWWWW....',
    '...WWWWWWWWwWWWWWWwwwwWWWWWW....',
    '...WWWWWWWWWWWWWWWwwwWwWWWWW....',
    '....WWWWwWWWWWWWWwwwwWWWWWW.....',
    '.....WWWWWWWWWWWwwwwWWWWWW......',
    '.......WWoooWWWWWWWoooWW........',
    '.........OOOWWWWWWWOOO..........',
    '.........OOO...W...OOO..........',
  ],
  swim1: [
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '...................WWWWW........',
    '.................WWWWWWWWW......',
    '................WWWWWW.WWWW.....',
    '...............WWWWWWWKKWWWW....',
    '...............WWWWWWWKwWWWW....',
    '..............WWWWWWWWKKWWOOOO..',
    '..............WWWWWWPPWWWWOOOO..',
    '..............WWWWWWWWWWWOOOOO..',
    '..............WWWWWWWWWWWoooO...',
    '..............WWWWWWWWWWWoooW...',
    '..............WWWWWWWWWWWWWWW...',
    '.........WWWWWWWWWWWWWWWWWWWW...',
    '.......WWWWWWWWWwwwwWWWWWWWW....',
    '.....WWWWWWWWWWWWwwwwWWWWWWW....',
    '....WWWWWWWWWWWWWWwwwWWWWWW.....',
    '...WWWWWWwWWWWWWWWwwwwWWWWWW....',
    '...WWWWWWWWWWWWWWWWwwwwWWWWW....',
    '...WWWWWWWwWWWWWWWWwwwwWWWWW....',
    '..WWWWWWWWWWWWWWWWWwwwwWWWWWW...',
    '...WWWWWWWWWWWWWWWWwwwwWWWWW....',
    '...WWWWWWWWwWWWWWWwwwwWWWWWW....',
    '...WWWWWWWWWWWWWWWwwwWwWWWWW....',
    '....WWWWwWWWWWWWWwwwwWWWWWW.....',
    '.....WWWWWWWWWWWwwwwWWWWWW......',
    '.BBBBB.BBBBWWBBBBBBWWBBBB.BBBBB.',
    '...bbbb..bbbbbWWbbbbWW.bbbbbbbb.',
    '...............W................',
  ],
  swim2: [
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '...................WWWWW........',
    '.................WWWWWWWWW......',
    '................WWWWWW.WWWW.....',
    '...............WWWWWWWKKWWWW....',
    '...............WWWWWWWKwWWWW....',
    '..............WWWWWWWWKKWWOOOO..',
    '..............WWWWWWPPWWWWOOOO..',
    '..............WWWWWWWWWWWOOOOO..',
    '..............WWWWWWWWWWWoooO...',
    '..............WWWWWWWWWWWoooW...',
    '..............WWWWWWWWWWWWWWW...',
    '.........WWWWWWWWWWWWWWWWWWWW...',
    '.......WWWWWWWWWwwwwWWWWWWWW....',
    '.....WWWWWWWWWWWWwwwwWWWWWWW....',
    '....WWWWWWWWWWWWWWwwwWWWWWW.....',
    '...WWWWWWwWWWWWWWWwwwwWWWWWW....',
    '...WWWWWWWWWWWWWWWWwwwwWWWWW....',
    '...WWWWWWWwWWWWWWWWwwwwWWWWW....',
    '..WWWWWWWWWWWWWWWWWwwwwWWWWWW...',
    '...WWWWWWWWWWWWWWWWwwwwWWWWW....',
    '...WWWWWWWWwWWWWWWwwwwWWWWWW....',
    '...WWWWWWWWWWWWWWWwwwWwWWWWW....',
    '....WWWWwWWWWWWWWwwwwWWWWWW.....',
    '.....WWWWWWWWWWWwwwwWWWWWW......',
    'BBBB.BBBBBWWBBBBWWBBBBBW.BBBB...',
    '..bbbbb..WbbbbWWWbbbbb..bbbb.bb.',
    '...............W................',
  ],
  dive1: [
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................OOO.............',
    '................OOO.............',
    '..........OOO...OOO.............',
    '..........OOO.W.OOO.............',
    '.........WOOOWWWOOOW............',
    '.......WWWOOOWWWWWWWWW..........',
    '.....WWWWWWWWWWWWWWWWWWW........',
    '....WWWWWWWWWWWWWWWWWWWWW.......',
    '...WWWWWwWWWWWWWWWWWWWWWWW......',
    '...WWWWWWWWWWWWWWWWwWWWWWW......',
    '...WWWWWWWWWWWWWWWWWWWWWWW......',
    '..WWWWWWWWWWWWWWWWWWWWWWWWW.....',
    '...WWWWWWWWWWWWWWWWWWWWWWW......',
    '...WWWWWWWWWwWWWWWWWWWWWWW......',
    '...WWWWWWWWWWWWWWWWWWWWWWW......',
    'bbbbbbbWWBBBBBBBWWWbbbbbbbb.BBBB',
    '..BBBBBBBWWWbbbbbbbbbWWBBBBBBBB.',
    '.......WWWWWWWWWWWWWWW..........',
    '.........WWWWWWWWWWW............',
  ],
  dive2: [
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '........OOO.....................',
    '........OOO.......OOO...........',
    '........OOO...W...OOO...........',
    '........OOOWWWWWWWOOO...........',
    '.......WWWWWWWWWWWOOOW..........',
    '.....WWWWWWWWWWWWWWWWWWW........',
    '....WWWWWWWWWWWWWWWWWWWWW.......',
    '...WWWWWwWWWWWWWWWWWWWWWWW......',
    '...WWWWWWWWWWWWWWWWwWWWWWW......',
    '...WWWWWWWWWWWWWWWWWWWWWWW......',
    '..WWWWWWWWWWWWWWWWWWWWWWWWW.....',
    '...WWWWWWWWWWWWWWWWWWWWWWW......',
    '...WWWWWWWWWwWWWWWWWWWWWWW......',
    '...WWWWWWWWWWWWWWWWWWWWWWW......',
    'bbbbbbbWWBBBBBBBWWWbbbbbbbb.BBBB',
    '..BBBBBBBWWWbbbbbbbbbWWBBBBBBBB.',
    '.......WWWWWWWWWWWWWWW..........',
    '.........WWWWWWWWWWW............',
  ],
  code1: [
    '..........................................',
    '..........................................',
    '..........................................',
    '..........................................',
    '..........................................',
    '...................WWWWW..................',
    '.................WWWWWWWWW................',
    '................WWWWWW.WWWW...............',
    '...............WWWWWWWKKWWWW..............',
    '...............WWWWWWWKwWWWW..............',
    '..............WWWWWWWWKKWWOOOO............',
    '..............WWWWWWPPWWWWOOOO............',
    '..............WWWWWWWWWWWOOOOO............',
    '..............WWWWWWWWWWWoooO..GGGGGGGGGG.',
    '..............WWWWWWWWWWWoooW..GSSSSSSSSG.',
    '..............WWWWWWWWWWWWWWW..GSSSSSSSSG.',
    '.........WWWWWWWWWWWWWWWWWWWW..GSsSSsSSSG.',
    '.......WWWWWWWWWwwwwWWWWWWWW...GSSSSSSSSG.',
    '.....WWWWWWWWWWWWwwwwWWWWWWW...GSSsSSsSSG.',
    '....WWWWWWWWWWWWWWwwwWWWWWW....GSSSSSSSSG.',
    '...WWWWWWwWWWWWWWWwwwwWWWWWW...GSsSSSSSSG.',
    '...WWWWWWWWWWWWWWWWwwwwWWWWW...GSSSSSSSSG.',
    '...WWWWWWWwWWWWWWWWwwwwWWWWW...gggggggggg.',
    '..WWWWWWWWWWWWWWWWWwwwwWWWWWW..gggggggggg.',
    '...WWWWWWWWWWWWWWWWwwwwWWWWW...gggggggggg.',
    '...WWWWWWWWwWWWWWWwwwwWWWWWW..............',
    '...WWWWWWWWWWWWWWWwwwWwWWWWW..............',
    '....WWWWwWWWWWWWWwwwwWWWWWW...............',
    '.....WWWWWWWWWWWwwwwWWWWWW................',
    '.......WWoooWWWWWWWoooWW..................',
    '.........OOOWWWWWWWOOO....................',
    '.........OOO...W...OOO....................',
  ],
  code2: [
    '..........................................',
    '..........................................',
    '..........................................',
    '..........................................',
    '..........................................',
    '...................WWWWW..................',
    '.................WWWWWWWWW................',
    '................WWWWWW.WWWW...............',
    '...............WWWWWWWKKWWWW..............',
    '...............WWWWWWWKwWWWW..............',
    '..............WWWWWWWWKKWWOOOO............',
    '..............WWWWWWPPWWWWOOOO............',
    '..............WWWWWWWWWWWOOOOO............',
    '..............WWWWWWWWWWWoooO..GGGGGGGGGG.',
    '..............WWWWWWWWWWWoooW..GSSSSSSSSG.',
    '..............WWWWWWWWWWWWWWW..GSSSSSSSSG.',
    '.........WWWWWWWWWWWWWWWWWWWW..GSSsSSsSSG.',
    '.......WWWWWWWWWwwwwWWWWWWWW...GSSSSSSSSG.',
    '.....WWWWWWWWWWWWwwwwWWWWWWW...GSsSSsSSSG.',
    '....WWWWWWWWWWWWWWwwwWWWWWW....GSSSSSSSSG.',
    '...WWWWWWwWWWWWWWWwwwwWWWWWW...GSSSsSSSSG.',
    '...WWWWWWWWWWWWWWWWwwwwWWWWW...GSSSSSSSSG.',
    '...WWWWWWWwWWWWWWWWwwwwWWWWW...gggggggggg.',
    '..WWWWWWWWWWWWWWWWWwwwwWWWWWW..gggggggggg.',
    '...WWWWWWWWWWWWWWWWwwwwWWWWW...gggggggggg.',
    '...WWWWWWWWwWWWWWWwwwwWWWWWW..............',
    '...WWWWWWWWWWWWWWWwwwWwWWWWW..............',
    '....WWWWwWWWWWWWWwwwwWWWWWW...............',
    '.....WWWWWWWWWWWwwwwWWWWWW................',
    '.......WWoooWWWWWWWoooWW..................',
    '.........OOOWWWWWWWOOO....................',
    '.........OOO...W...OOO....................',
  ],
  think1: [
    '................................',
    '...........................D....',
    '................................',
    '........................D.......',
    '................................',
    '...................WWWWW........',
    '.................WWWWWWWWW......',
    '................WWWWWW.WWWW.....',
    '...............WWWWWWWKKWWWW....',
    '...............WWWWWWWKwWWWW....',
    '..............WWWWWWWWKKWWOOOO..',
    '..............WWWWWWPPWWWWOOOO..',
    '..............WWWWWWWWWWWOOOOO..',
    '..............WWWWWWWWWWWoooO...',
    '..............WWWWWWWWWWWoooW...',
    '..............WWWWWWWWWWWWWWW...',
    '.........WWWWWWWWWWWWWWWWWWWW...',
    '.......WWWWWWWWWwwwwWWWWWWWW....',
    '.....WWWWWWWWWWWWwwwwWWWWWWW....',
    '....WWWWWWWWWWWWWWwwwWWWWWW.....',
    '...WWWWWWwWWWWWWWWwwwwWWWWWW....',
    '...WWWWWWWWWWWWWWWWwwwwWWWWW....',
    '...WWWWWWWwWWWWWWWWwwwwWWWWW....',
    '..WWWWWWWWWWWWWWWWWwwwwWWWWWW...',
    '...WWWWWWWWWWWWWWWWwwwwWWWWW....',
    '...WWWWWWWWwWWWWWWwwwwWWWWWW....',
    '...WWWWWWWWWWWWWWWwwwWwWWWWW....',
    '....WWWWwWWWWWWWWwwwwWWWWWW.....',
    '.....WWWWWWWWWWWwwwwWWWWWW......',
    '.......WWoooWWWWWWWoooWW........',
    '.........OOOWWWWWWWOOO..........',
    '.........OOO...W...OOO..........',
  ],
  think2: [
    '............................D...',
    '................................',
    '.........................D......',
    '................................',
    '.......................D........',
    '...................WWWWW........',
    '.................WWWWWWWWW......',
    '................WWWWWW.WWWW.....',
    '...............WWWWWWWKKWWWW....',
    '...............WWWWWWWKwWWWW....',
    '..............WWWWWWWWKKWWOOOO..',
    '..............WWWWWWPPWWWWOOOO..',
    '..............WWWWWWWWWWWOOOOO..',
    '..............WWWWWWWWWWWoooO...',
    '..............WWWWWWWWWWWoooW...',
    '..............WWWWWWWWWWWWWWW...',
    '.........WWWWWWWWWWWWWWWWWWWW...',
    '.......WWWWWWWWWwwwwWWWWWWWW....',
    '.....WWWWWWWWWWWWwwwwWWWWWWW....',
    '....WWWWWWWWWWWWWWwwwWWWWWW.....',
    '...WWWWWWwWWWWWWWWwwwwWWWWWW....',
    '...WWWWWWWWWWWWWWWWwwwwWWWWW....',
    '...WWWWWWWwWWWWWWWWwwwwWWWWW....',
    '..WWWWWWWWWWWWWWWWWwwwwWWWWWW...',
    '...WWWWWWWWWWWWWWWWwwwwWWWWW....',
    '...WWWWWWWWwWWWWWWwwwwWWWWWW....',
    '...WWWWWWWWWWWWWWWwwwWwWWWWW....',
    '....WWWWwWWWWWWWWwwwwWWWWWW.....',
    '.....WWWWWWWWWWWwwwwWWWWWW......',
    '.......WWoooWWWWWWWoooWW........',
    '.........OOOWWWWWWWOOO..........',
    '.........OOO...W...OOO..........',
  ],
  thinkcap1: [
    '................................',
    '................................',
    '.................CCCCCCCCCT.....',
    '.................CCCCCCCCCT.....',
    '...................CCCCC..T.....',
    '...................WCCCW..T.....',
    '.................WWWWWWWWWT.....',
    '................WWWWWW.WWWT.....',
    '...............WWWWWWWKKWWWW....',
    '...............WWWWWWWKwWWWW....',
    '..............WWWWWWWWKKWWOOOO..',
    '..............WWWWWWPPWWWWOOOO..',
    '..............WWWWWWWWWWWOOOOO..',
    '..............WWWWWWWWWWWoooO...',
    '..............WWWWWWWWWWWoooW...',
    '..............WWWWWWWWWWWWWWW...',
    '.........WWWWWWWWWWWWWWWWWWWW...',
    '.......WWWWWWWWWwwwwWWWWWWWW....',
    '.....WWWWWWWWWWWWwwwwWWWWWWW....',
    '....WWWWWWWWWWWWWWwwwWWWWWW.....',
    '...WWWWWWwWWWWWWWWwwwwWWWWWW....',
    '...WWWWWWWWWWWWWWWWwwwwWWWWW....',
    '...WWWWWWWwWWWWWWWWwwwwWWWWW....',
    '..WWWWWWWWWWWWWWWWWwwwwWWWWWW...',
    '...WWWWWWWWWWWWWWWWwwwwWWWWW....',
    '...WWWWWWWWwWWWWWWwwwwWWWWWW....',
    '...WWWWWWWWWWWWWWWwwwWwWWWWW....',
    '....WWWWwWWWWWWWWwwwwWWWWWW.....',
    '.....WWWWWWWWWWWwwwwWWWWWW......',
    '.......WWoooWWWWWWWoooWW........',
    '.........OOOWWWWWWWOOO..........',
    '.........OOO...W...OOO..........',
  ],
  thinkcap2: [
    '................................',
    '................................',
    '................TCCCCCCCCC......',
    '................TCCCCCCCCC......',
    '................T..CCCCC........',
    '................T..WCCCW........',
    '................TWWWWWWWWW......',
    '................TWWWWW.WWWW.....',
    '...............WWWWWWWKKWWWW....',
    '...............WWWWWWWKwWWWW....',
    '..............WWWWWWWWKKWWOOOO..',
    '..............WWWWWWPPWWWWOOOO..',
    '..............WWWWWWWWWWWOOOOO..',
    '..............WWWWWWWWWWWoooO...',
    '..............WWWWWWWWWWWoooW...',
    '..............WWWWWWWWWWWWWWW...',
    '.........WWWWWWWWWWWWWWWWWWWW...',
    '.......WWWWWWWWWwwwwWWWWWWWW....',
    '.....WWWWWWWWWWWWwwwwWWWWWWW....',
    '....WWWWWWWWWWWWWWwwwWWWWWW.....',
    '...WWWWWWwWWWWWWWWwwwwWWWWWW....',
    '...WWWWWWWWWWWWWWWWwwwwWWWWW....',
    '...WWWWWWWwWWWWWWWWwwwwWWWWW....',
    '..WWWWWWWWWWWWWWWWWwwwwWWWWWW...',
    '...WWWWWWWWWWWWWWWWwwwwWWWWW....',
    '...WWWWWWWWwWWWWWWwwwwWWWWWW....',
    '...WWWWWWWWWWWWWWWwwwWwWWWWW....',
    '....WWWWwWWWWWWWWwwwwWWWWWW.....',
    '.....WWWWWWWWWWWwwwwWWWWWW......',
    '.......WWoooWWWWWWWoooWW........',
    '.........OOOWWWWWWWOOO..........',
    '.........OOO...W...OOO..........',
  ],
  search1: [
    '................................',
    '................................',
    '................................',
    '.....MMM........................',
    '....MMLMM.......................',
    '...MMLLLMM.........WWWWW........',
    '...MLLLLLM.......WWWWWWWWW......',
    '...MMLLLMM......WWWWWW.WWWW.....',
    '....MMLMM......WWWWWWWKKWWWW....',
    '...A.MMM.......WWWWWWWKwWWWW....',
    '..A...........WWWWWWWWKKWWOOOO..',
    '..A...........WWWWWWPPWWWWOOOO..',
    '.A............WWWWWWWWWWWOOOOO..',
    '..............WWWWWWWWWWWoooO...',
    '..............WWWWWWWWWWWoooW...',
    '..............WWWWWWWWWWWWWWW...',
    '.........WWWWWWWWWWWWWWWWWWWW...',
    '.......WWWWWWWWWwwwwWWWWWWWW....',
    '.....WWWWWWWWWWWWwwwwWWWWWWW....',
    '....WWWWWWWWWWWWWWwwwWWWWWW.....',
    '...WWWWWWwWWWWWWWWwwwwWWWWWW....',
    '...WWWWWWWWWWWWWWWWwwwwWWWWW....',
    '...WWWWWWWwWWWWWWWWwwwwWWWWW....',
    '..WWWWWWWWWWWWWWWWWwwwwWWWWWW...',
    '...WWWWWWWWWWWWWWWWwwwwWWWWW....',
    '...WWWWWWWWwWWWWWWwwwwWWWWWW....',
    '...WWWWWWWWWWWWWWWwwwWwWWWWW....',
    '....WWWWwWWWWWWWWwwwwWWWWWW.....',
    '.....WWWWWWWWWWWwwwwWWWWWW......',
    '.......WWoooWWWWWWWoooWW........',
    '.........OOOWWWWWWWOOO..........',
    '.........OOO...W...OOO..........',
  ],
  search2: [
    '................................',
    '................................',
    '................................',
    '.....MMM........................',
    '....MMLMM.......................',
    '...MMLLLMM.........WWWWW........',
    '...MLLLLLM.......WWWWWWWWW......',
    '...MMLLLMM......WWWWWW.WWWW.....',
    '....MMLMM......WWWWWWWKKWWWW....',
    '...A.MMM.......WWWWWWWKwWWWW....',
    '..A...........WWWWWWWWKKWWOOOO..',
    '..A...........WWWWWWPPWWWWOOOO..',
    '.A............WWWWWWWWWWWOOOOO..',
    '..............WWWWWWWWWWWoooO...',
    '..............WWWWWWWWWWWoooW...',
    '..............WWWWWWWWWWWWWWW...',
    '.........WWWWWWWWWWWWWWWWWWWW...',
    '.......WWWWWWWWWwwwwWWWWWWWW....',
    '.....WWWWWWWWWWWWwwwwWWWWWWW....',
    '....WWWWWWWWWWWWWWwwwWWWWWW.....',
    '...WWWWWWwWWWWWWWWwwwwWWWWWW....',
    '...WWWWWWWWWWWWWWWWwwwwWWWWW....',
    '...WWWWWWWwWWWWWWWWwwwwWWWWW....',
    '..WWWWWWWWWWWWWWWWWwwwwWWWWWW...',
    '...WWWWWWWWWWWWWWWWwwwwWWWWW....',
    '...WWWWWWWWwWWWWWWwwwwWWWWWW....',
    '...WWWWWWWWWWWWWWWwwwWwWWWWW....',
    '....WWWWwWWWWWWWWwwwwWWWWWW.....',
    '.....WWWWWWWWWWWwwwwWWWWWW......',
    '.......WWoooWWWWWWWoooWW........',
    '.........OOOWWWWWWWOOO..........',
    '.........OOO...W...OOO..........',
  ],
  image1: [
    '................................',
    'EEEEEEEEEEE.....................',
    'EWWWWWWWWWE.....................',
    'EWHHHWWWWWE.....................',
    'EWHHHWWWWWE.....................',
    'EWHHHWWWWWE........WWWWW........',
    'EWWWWWWWWWE......WWWWWWWWW......',
    'EWWWWWwwwWE.....WWWWWW.WWWW.....',
    'EWWWWWwwwWE....WWWWWWWKKWWWW....',
    'EWWWWWwwwWE....WWWWWWWKwWWWW....',
    'EWWWWWWWWWE...WWWWWWWWKKWWOOOO..',
    'EEEEEEEEEEE...WWWWWWPPWWWWOOOO..',
    '....A.........WWWWWWWWWWWOOOOO..',
    '....AA........WWWWWWWWWWWoooO...',
    '....AA........WWWWWWWWWWWoooW...',
    '....AA........WWWWWWWWWWWWWWW...',
    '....AA...WWWWWWWWWWWWWWWWWWWW...',
    '....A..WWWWWWWWWwwwwWWWWWWWW....',
    '.....WWWWWWWWWWWWwwwwWWWWWWW....',
    '....WWWWWWWWWWWWWWwwwWWWWWW.....',
    '...WWWWWWwWWWWWWWWwwwwWWWWWW....',
    '...WWWWWWWWWWWWWWWWwwwwWWWWW....',
    '...WWWWWWWwWWWWWWWWwwwwWWWWW....',
    '..WWWWWWWWWWWWWWWWWwwwwWWWWWW...',
    '...WWWWWWWWWWWWWWWWwwwwWWWWW....',
    '...WWWWWWWWwWWWWWWwwwwWWWWWW....',
    '...WWWWWWWWWWWWWWWwwwWwWWWWW....',
    '....WWWWwWWWWWWWWwwwwWWWWWW.....',
    '.....WWWWWWWWWWWwwwwWWWWWW......',
    '.......WWoooWWWWWWWoooWW........',
    '.........OOOWWWWWWWOOO..........',
    '.........OOO...W...OOO..........',
  ],
  image2: [
    '................................',
    'EEEEEEEEEEE.....................',
    'EWWWWWWWWWE.....................',
    'EWWWWWHHHWE.....................',
    'EWWWWWHHHWE.....................',
    'EWWWWWHHHWE........WWWWW........',
    'EWWWWWWWWWE......WWWWWWWWW......',
    'EWwwwWWWWWE.....WWWWWW.WWWW.....',
    'EWwwwWWWWWE....WWWWWWWKKWWWW....',
    'EWwwwWWWWWE....WWWWWWWKwWWWW....',
    'EWWWWWWWWWE...WWWWWWWWKKWWOOOO..',
    'EEEEEEEEEEE...WWWWWWPPWWWWOOOO..',
    '....A.........WWWWWWWWWWWOOOOO..',
    '....AA........WWWWWWWWWWWoooO...',
    '....AA........WWWWWWWWWWWoooW...',
    '....AA........WWWWWWWWWWWWWWW...',
    '....AA...WWWWWWWWWWWWWWWWWWWW...',
    '....A..WWWWWWWWWwwwwWWWWWWWW....',
    '.....WWWWWWWWWWWWwwwwWWWWWWW....',
    '....WWWWWWWWWWWWWWwwwWWWWWW.....',
    '...WWWWWWwWWWWWWWWwwwwWWWWWW....',
    '...WWWWWWWWWWWWWWWWwwwwWWWWW....',
    '...WWWWWWWwWWWWWWWWwwwwWWWWW....',
    '..WWWWWWWWWWWWWWWWWwwwwWWWWWW...',
    '...WWWWWWWWWWWWWWWWwwwwWWWWW....',
    '...WWWWWWWWwWWWWWWwwwwWWWWWW....',
    '...WWWWWWWWWWWWWWWwwwWwWWWWW....',
    '....WWWWwWWWWWWWWwwwwWWWWWW.....',
    '.....WWWWWWWWWWWwwwwWWWWWW......',
    '.......WWoooWWWWWWWoooWW........',
    '.........OOOWWWWWWWOOO..........',
    '.........OOO...W...OOO..........',
  ],
  talk2: [
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '...................WWWWW........',
    '.................WWWWWWWWW......',
    '................WWWWWW.WWWW.....',
    '...............WWWWWWWKKWWWW....',
    '...............WWWWWWWKwWWWW....',
    '..............WWWWWWWWKKWWOOOO..',
    '..............WWWWWWPPWWWWOOOO..',
    '..............WWWWWWWWWWWOOOOO..',
    '..............WWWWWWWWWWWoooO...',
    '..............WWWWWWWWWWWoo.W...',
    '..............WWWWWWWWWWWWWWD...',
    '.........WWWWWWWWWWWWWWWWWWWW...',
    '.......WWWWWWWWWwwwwWWWWWWWW....',
    '.....WWWWWWWWWWWWwwwwWWWWWWW....',
    '....WWWWWWWWWWWWWWwwwWWWWWW.....',
    '...WWWWWWwWWWWWWWWwwwwWWWWWW....',
    '...WWWWWWWWWWWWWWWWwwwwWWWWW....',
    '...WWWWWWWwWWWWWWWWwwwwWWWWW....',
    '..WWWWWWWWWWWWWWWWWwwwwWWWWWW...',
    '...WWWWWWWWWWWWWWWWwwwwWWWWW....',
    '...WWWWWWWWwWWWWWWwwwwWWWWWW....',
    '...WWWWWWWWWWWWWWWwwwWwWWWWW....',
    '....WWWWwWWWWWWWWwwwwWWWWWW.....',
    '.....WWWWWWWWWWWwwwwWWWWWW......',
    '.......WWoooWWWWWWWoooWW........',
    '.........OOOWWWWWWWOOO..........',
    '.........OOO...W...OOO..........',
  ],
  stretch1: [
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '...................WWWWW........',
    '.................WWWWWWWWW......',
    '................WWWWWW.WWWW.....',
    '.WW............WWWWWWWKKWWWW....',
    '.WW............WWWWWWWKwWWWW....',
    'WWWW..........WWWWWWWWKKWWOOOO..',
    'WWWW..........WWWWWWPPWWWWOOOO..',
    'WWWW..........WWWWWWWWWWWOOOOO..',
    'WWWW..........WWWWWWWWWWWoooO...',
    'WWWWW.........WWWWWWWWWWWoooW...',
    '.WWWW.........WWWWWWWWWWWWWWW...',
    '.WWWW....WWWWWWWWWWWWWWWWWWWW...',
    '.WWWW..WWWWWWWWWwwwwWWWWWWWW....',
    '.WWWWWWWWWWWWWWWWwwwwWWWWWWW....',
    '....WWWWWWWWWWWWWWwwwWWWWWW.....',
    '...WWWWWWwWWWWWWWWwwwwWWWWWW....',
    '...WWWWWWWWWWWWWWWWwwwwWWWWW....',
    '...WWWWWWWwWWWWWWWWwwwwWWWWW....',
    '..WWWWWWWWWWWWWWWWWwwwwWWWWWW...',
    '...WWWWWWWWWWWWWWWWwwwwWWWWW....',
    '...WWWWWWWWwWWWWWWwwwwWWWWWW....',
    '...WWWWWWWWWWWWWWWwwwWwWWWWW....',
    '....WWWWwWWWWWWWWwwwwWWWWWW.....',
    '.....WWWWWWWWWWWwwwwWWWWWW......',
    '.......WWoooWWWWWWWoooWW........',
    '.........OOOWWWWWWWOOO..........',
    '.........OOO...W...OOO..........',
  ],
  stretch2: [
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '...................WWWWW........',
    'WWWW.............WWWWWWWWW......',
    'WWWW............WWWWWW.WWWW.....',
    'WWWW...........WWWWWWWKKWWWW....',
    'WWWWW..........WWWWWWWKwWWWW....',
    'WWWWW.........WWWWWWWWKKWWOOOO..',
    'WWWWW.........WWWWWWPPWWWWOOOO..',
    'WWWWW.........WWWWWWWWWWWOOOOO..',
    'WWWWW.........WWWWWWWWWWWoooO...',
    'WWWWW.........WWWWWWWWWWWoooW...',
    '.wwwW.........WWWWWWWWWWWWWWW...',
    '.wwwW....WWWWWWWWWWWWWWWWWWWW...',
    '.WWWW..WWWWWWWWWwwwwWWWWWWWW....',
    '.WWWWWWWWWWWWWWWWwwwwWWWWWWW....',
    '....WWWWWWWWWWWWWWwwwWWWWWW.....',
    '...WWWWWWwWWWWWWWWwwwwWWWWWW....',
    '...WWWWWWWWWWWWWWWWwwwwWWWWW....',
    '...WWWWWWWwWWWWWWWWwwwwWWWWW....',
    '..WWWWWWWWWWWWWWWWWwwwwWWWWWW...',
    '...WWWWWWWWWWWWWWWWwwwwWWWWW....',
    '...WWWWWWWWwWWWWWWwwwwWWWWWW....',
    '...WWWWWWWWWWWWWWWwwwWwWWWWW....',
    '....WWWWwWWWWWWWWwwwwWWWWWW.....',
    '.....WWWWWWWWWWWwwwwWWWWWW......',
    '.......WWoooWWWWWWWoooWW........',
    '.........OOOWWWWWWWOOO..........',
    '.........OOO...W...OOO..........',
  ],
  preen1: [
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '...................WWWWW........',
    '.................WWWWWWWWW......',
    '................WWWWWWWWWWW.....',
    '...............WWWWWWWWWWWWW....',
    '...............WWWWWWWKKWWWW....',
    '..............WWWWWWWWKwWWOOOO..',
    '..............WWWWWWPPWWWWOOOO..',
    '..............WWWWWWWWWWWOOOOO..',
    '..............WWWWWWWWWWWoooO...',
    '.........WWWWWWWWWWWWWWWWoooW...',
    '.......WWWWWWWWWwwwwWWWWWWWWW...',
    '.....WWWWWWWWWWWWwwwwWWWWWWWW...',
    '....WWWWWWWWWWWWWWwwwWWWWWWW....',
    '...WWWWWWwWWWWWWWWwwwwWWWWWW....',
    '...WWWWWWWWWWWWWWWWwwwwWWWWW....',
    '...WWWWWWWwWWWWWWWWwwwwWWWWW....',
    '..WWWWWWWWWWWWWWWWWwwwwWWWWWW...',
    '...WWWWWWWWWWWWWWWWwwwwWWWWW....',
    '...WWWWWWWWwWWWWWWwwwwWWWWWW....',
    '...WWWWWWWWWWWWWWWwwwWwWWWWW....',
    '....WWWWwWWWWWWWWwwwwWWWWWW.....',
    '.....WWWWWWWWWWWwwwwWWWWWW......',
    '.......WWoooWWWWWWWoooWW........',
    '.........OOOWWWWWWWOOO..........',
    '.........OOO...W...OOO..........',
  ],
  preen2: [
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '...................WWWWW........',
    '.................WWWWWWWWW......',
    '................WWWWWWWWWWW.....',
    '...............WWWWWWWWWWWWW....',
    '...............WWWWWWWKKWWWW....',
    '..............WWWWWWWWKwWWOOOO..',
    '..............WWWWWWPPWWWWOOOO..',
    '..............WWWWWWWWWWWOOOOO..',
    '..............WWWWWWWWWWWoooO...',
    '.........WWWWWWWWWWWWWWWWoooW...',
    '.......WWWWWWWWWwwwwWWWWWWWWW...',
    '.....WWWWWWWWWWWWwwwwWWWWWWWW...',
    '....WWWWWWWWWWWWWWwwwWWWWWWW....',
    '...WWwwWWwWWWWWWWWwwwwWWWWWW....',
    '...WWWWWWWWWWWWWWWWwwwwWWWWW....',
    '...WWWWWWWwWWWWWWWWwwwwWWWWW....',
    '..WWWWWWWWWWWWWWWWWwwwwWWWWWW...',
    '...WWWWWWWWWWWWWWWWwwwwWWWWW....',
    '...WWWWWWWWwWWWWWWwwwwWWWWWW....',
    '...WWWWWWWWWWWWWWWwwwWwWWWWW....',
    '....WWWWwWWWWWWWWwwwwWWWWWW.....',
    '.....WWWWWWWWWWWwwwwWWWWWW......',
    '.......WWoooWWWWWWWoooWW........',
    '.........OOOWWWWWWWOOO..........',
    '.........OOO...W...OOO..........',
  ],
  quack1: [
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '...................WWWWW........',
    '.................WWWWWWWWW......',
    '................WWWWWW.WWWQ.....',
    '...............WWWWWWWKKWWWW....',
    '...............WWWWWWWKwWWWW....',
    '..............WWWWWWWWKKWWOOOO..',
    '..............WWWWWWPPWWWWOOOO..',
    '..............WWWWWWWWWWWOOOOO..',
    '..............WWWWWWWWWWWoooO...',
    '..............WWWWWWWWWWWoo.W...',
    '..............WWWWWWWWWWWWWWW...',
    '.........WWWWWWWWWWWWWWWWWWWW...',
    '.......WWWWWWWWWwwwwWWWWWWWW....',
    '.....WWWWWWWWWWWWwwwwWWWWWWW....',
    '....WWWWWWWWWWWWWWwwwWWWWWW.....',
    '...WWWWWWwWWWWWWWWwwwwWWWWWW....',
    '...WWWWWWWWWWWWWWWWwwwwWWWWW....',
    '...WWWWWWWwWWWWWWWWwwwwWWWWW....',
    '..WWWWWWWWWWWWWWWWWwwwwWWWWWW...',
    '...WWWWWWWWWWWWWWWWwwwwWWWWW....',
    '...WWWWWWWWwWWWWWWwwwwWWWWWW....',
    '...WWWWWWWWWWWWWWWwwwWwWWWWW....',
    '....WWWWwWWWWWWWWwwwwWWWWWW.....',
    '.....WWWWWWWWWWWwwwwWWWWWW......',
    '.......WWoooWWWWWWWoooWW........',
    '.........OOOWWWWWWWOOO..........',
    '.........OOO...W...OOO..........',
  ],
  quack2: [
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '...................WWWWW........',
    '.................WWWWWWWWW.Q....',
    '................WWWWWW.WWWW.....',
    '...............WWWWWWWKKWQWW....',
    '...............WWWWWWWKwWWWW....',
    '..............WWWWWWWWKKWWOOOO..',
    '..............WWWWWWPPWWWWOOOO..',
    '..............WWWWWWWWWWWOOOOO..',
    '..............WWWWWWWWWWWoooO...',
    '..............WWWWWWWWWWWoo.W...',
    '..............WWWWWWWWWWWWWWW...',
    '.........WWWWWWWWWWWWWWWWWWWW...',
    '.......WWWWWWWWWwwwwWWWWWWWW....',
    '.....WWWWWWWWWWWWwwwwWWWWWWW....',
    '....WWWWWWWWWWWWWWwwwWWWWWW.....',
    '...WWWWWWwWWWWWWWWwwwwWWWWWW....',
    '...WWWWWWWWWWWWWWWWwwwwWWWWW....',
    '...WWWWWWWwWWWWWWWWwwwwWWWWW....',
    '..WWWWWWWWWWWWWWWWWwwwwWWWWWW...',
    '...WWWWWWWWWWWWWWWWwwwwWWWWW....',
    '...WWWWWWWWwWWWWWWwwwwWWWWWW....',
    '...WWWWWWWWWWWWWWWwwwWwWWWWW....',
    '....WWWWwWWWWWWWWwwwwWWWWWW.....',
    '.....WWWWWWWWWWWwwwwWWWWWW......',
    '.......WWoooWWWWWWWoooWW........',
    '.........OOOWWWWWWWOOO..........',
    '.........OOO...W...OOO..........',
  ],
};


const grey = '#9c9a96';
const accent = '#d9a05b';

export const ICONS = {
  // pushpin: head, flange, needle
  pin: {
    palette: { P: grey },
    map: [
      '...PPPP...',
      '...PPPP...',
      '...PPPP...',
      '..PPPPPP..',
      '.PPPPPPPP.',
      '....PP....',
      '....PP....',
      '....P.....',
    ],
  },
  pinOn: {
    palette: { P: accent },
    map: null, // filled below — same shape as pin
  },
  // settings: three sliders with offset knobs
  sliders: {
    palette: { G: '#55534f', K: grey },
    map: [
      '..KKK......',
      'GGKKKGGGGGG',
      '..KKK......',
      '...........',
      '.......KKK.',
      'GGGGGGGKKKG',
      '.......KKK.',
      '...........',
      '...KKK.....',
      'GGGKKKGGGGG',
      '...KKK.....',
    ],
  },
  plus: {
    palette: { P: '#e8e6e2' },
    map: [
      '...PP...',
      '...PP...',
      '...PP...',
      'PPPPPPPP',
      'PPPPPPPP',
      '...PP...',
      '...PP...',
      '...PP...',
    ],
  },
  arrowUp: {
    palette: { P: '#e8e6e2' },
    map: [
      '....P....',
      '...PPP...',
      '..PPPPP..',
      '.PPPPPPP.',
      'PPPPPPPPP',
      '...PPP...',
      '...PPP...',
      '...PPP...',
      '...PPP...',
    ],
  },
  stop: {
    palette: { P: '#c96a5b' },
    map: [
      '.PPPPPP.',
      'PPPPPPPP',
      'PPPPPPPP',
      'PPPPPPPP',
      'PPPPPPPP',
      'PPPPPPPP',
      'PPPPPPPP',
      '.PPPPPP.',
    ],
  },
};
ICONS.pinOn.map = ICONS.pin.map;

// action-row icons (grey; hover color handled in CSS via opacity)
ICONS.pencil = {
  palette: { P: grey },
  map: [
    '......PP.',
    '.....PPPP',
    '....PPPP.',
    '...PPPP..',
    '..PPPP...',
    '.PPPP....',
    'PPP......',
    'P........',
  ],
};
ICONS.trash = {
  palette: { P: grey },
  map: [
    '...PPP...',
    '.PPPPPPP.',
    '..PPPPP..',
    '..P.P.P..',
    '..P.P.P..',
    '..P.P.P..',
    '..PPPPP..',
    '...PPP...',
  ],
};
ICONS.copy = {
  palette: { P: grey },
  map: [
    '...PPPPPP.',
    '...P....P.',
    '...P....P.',
    'PPPPPP..P.',
    'P....P..P.',
    'P....PPPP.',
    'P....P....',
    'P....P....',
    'PPPPPP....',
  ],
};
ICONS.retry = {
  palette: { P: grey },
  map: [
    '...PPPP...',
    '..PP..PP..',
    '.PP....PP.',
    '.P.....PPP',
    '.P......P.',
    '.P.....PP.',
    '.PP....P..',
    '..PP..PP..',
    '...PPPP...',
  ],
};

// Merge horizontal runs of same-colored pixels into single rects.
export function buildRects(map, palette) {
  const rects = [];
  for (let y = 0; y < map.length; y++) {
    const row = map[y];
    let x = 0;
    while (x < row.length) {
      const ch = row[x];
      if (ch === '.' || !palette[ch]) { x++; continue; }
      let end = x + 1;
      while (end < row.length && row[end] === ch) end++;
      rects.push({ x, y, w: end - x, c: palette[ch] });
      x = end;
    }
  }
  return rects;
}

export function toSvg(map, palette, extraAttrs = '') {
  const w = map[0].length;
  const h = map.length;
  const body = buildRects(map, palette)
    .map((r) => `<rect x="${r.x}" y="${r.y}" width="${r.w}" height="1" fill="${r.c}"/>`)
    .join('');
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${w} ${h}" shape-rendering="crispEdges" ${extraAttrs}>${body}</svg>`;
}
