// Diffusion LLMs (LLaDA / Dream family): text is generated by iteratively
// denoising a fully-masked sequence — completely different from both
// autoregressive chat and image diffusion. We spawn llama-diffusion-cli in
// --diffusion-visual mode and forward every intermediate frame over SSE, so
// the UI can show the text literally taking shape.
import { spawn } from 'node:child_process';
import { existsSync, readdirSync, statSync } from 'node:fs';
import { basename, join } from 'node:path';
import { requireAuth } from '../auth.js';
import { listModels, unloadModel } from '../llama.js';

const BIN = process.env.DIFFUSION_CLI
  ?? '/home/cranky/bin/llama-prebuilt/b9966-vulkan/llama-diffusion-cli';
const MODELS_DIR = process.env.DIFFUSION_MODELS_DIR
  ?? '/home/lewis/llm-models/llama.cpp-models/diffusion';
const MAX_RUN_MS = 10 * 60 * 1000;

// one GPU → one denoising job at a time
let busy = false;

// eslint-disable-next-line no-control-regex
const ANSI = /\x1b\[[0-9;?]*[A-Za-z]|\x1b[c=>]|\r/g;
const CLEAR = /\x1b\[2J|\x1b\[H\x1b\[J|\x1b\[3J/;

function ggufModels() {
  if (!existsSync(MODELS_DIR)) return [];
  return readdirSync(MODELS_DIR)
    .filter((f) => f.endsWith('.gguf'))
    .map((f) => ({
      id: f.replace(/\.gguf$/, ''),
      file: f,
      size: statSync(join(MODELS_DIR, f)).size,
    }));
}

export default async function diffusionRoutes(app) {
  app.addHook('preHandler', requireAuth);

  app.get('/api/diffusion/models', async () => ({
    available: existsSync(BIN),
    busy,
    models: ggufModels(),
  }));

  // SSE: {type:'load'} while the model warms, {type:'step', n, steps, text}
  // per denoising frame, {type:'done', text, ms} — or {type:'error', message}.
  app.post('/api/diffusion/generate', async (req, reply) => {
    const { model, prompt, tokens = 96, steps = 64, temp = 0, algorithm = 4 } = req.body ?? {};
    if (!prompt?.trim()) return reply.code(400).send({ error: 'prompt required' });
    const entry = ggufModels().find((m) => m.id === model || m.file === model);
    if (!entry) return reply.code(400).send({ error: 'unknown diffusion model' });
    if (busy) return reply.code(409).send({ error: 'a diffusion run is already in progress' });
    busy = true;

    reply.raw.writeHead(200, {
      'content-type': 'text/event-stream',
      'cache-control': 'no-cache',
      connection: 'keep-alive',
    });
    const send = (obj) => {
      if (reply.raw.writableEnded || reply.raw.destroyed) return;
      try { reply.raw.write(`data: ${JSON.stringify(obj)}\n\n`); } catch { /* client gone */ }
    };

    const nSteps = Math.min(Math.max(Number(steps) || 64, 8), 256);
    const nTokens = Math.min(Math.max(Number(tokens) || 96, 16), 512);
    const t0 = Date.now();
    let child = null;
    let killed = false;
    try {
      // the denoiser needs the VRAM the chat models are holding
      const loaded = (await listModels().catch(() => []))
        .filter((m) => m.status === 'loaded');
      for (const m of loaded) {
        send({ type: 'load', text: `freeing VRAM (unloading ${m.id})…` });
        await unloadModel(m.id).catch(() => {});
      }
      send({ type: 'load', text: 'loading the diffusion model…' });

      child = spawn(BIN, [
        '-m', join(MODELS_DIR, basename(entry.file)),
        '-p', String(prompt).slice(0, 4000),
        '-n', String(nTokens),
        '--diffusion-steps', String(nSteps),
        '--diffusion-visual',
        '--diffusion-algorithm', String(Number(algorithm) || 4),
        '--temp', String(Number(temp) || 0),
        '-ngl', '99',
        '--no-warmup',
      ], { stdio: ['ignore', 'pipe', 'pipe'] });

      const killTimer = setTimeout(() => { killed = true; child.kill('SIGKILL'); }, MAX_RUN_MS);
      reply.raw.on('close', () => {
        if (child.exitCode === null) { killed = true; child.kill('SIGKILL'); }
      });

      // --diffusion-visual repaints the whole current sequence each step,
      // separated by terminal-clear escapes. Frames arrive faster than a
      // human can read — throttle to ~8 fps but never drop the newest frame.
      let buf = '';
      let frame = '';
      let step = 0;
      let lastSent = 0;
      let trailer = null; // pending timer for the newest unsent frame
      const emitFrame = (text) => {
        step += 1;
        frame = text;
        const now = Date.now();
        if (now - lastSent >= 120) {
          lastSent = now;
          clearTimeout(trailer);
          trailer = null;
          send({ type: 'step', n: step, steps: nSteps, text });
        } else if (!trailer) {
          trailer = setTimeout(() => {
            trailer = null;
            lastSent = Date.now();
            send({ type: 'step', n: step, steps: nSteps, text: frame });
          }, 130);
        }
      };
      child.stdout.on('data', (d) => {
        buf += d.toString('utf8');
        const parts = buf.split(CLEAR);
        if (parts.length > 1) {
          for (const p of parts.slice(0, -1)) {
            const text = p.replace(ANSI, '');
            if (text.trim()) emitFrame(text);
          }
          buf = parts[parts.length - 1];
        }
      });
      let errTail = '';
      child.stderr.on('data', (d) => {
        errTail = (errTail + d.toString('utf8')).slice(-4000);
      });

      const code = await new Promise((res) => child.on('close', res));
      clearTimeout(killTimer);
      const final = buf.replace(ANSI, '').trim() || frame.trim();
      if (killed) {
        send({ type: 'done', text: final, stopped: true, ms: Date.now() - t0 });
      } else if (code !== 0 && !final) {
        req.log.error({ code, errTail }, 'diffusion cli failed');
        send({ type: 'error', message: `diffusion run failed (exit ${code}): ${errTail.split('\n').filter(Boolean).pop() ?? ''}` });
      } else {
        send({ type: 'done', text: final, ms: Date.now() - t0 });
      }
    } catch (err) {
      req.log.error({ err }, 'diffusion generation failed');
      send({ type: 'error', message: String(err.message ?? err) });
      if (child && child.exitCode === null) child.kill('SIGKILL');
    } finally {
      busy = false;
      if (!reply.raw.writableEnded) reply.raw.end();
    }
  });
}
