import assert from 'node:assert/strict';
import { estimateAgentPrompt, agentInputLimit, calibratedPromptEstimate, trimAgentToolHistory } from '../src/agentContext.js';
const messages = [{ role:'user', content:'Fix the build' }];
const before = estimateAgentPrompt(messages);
messages.push({ role:'assistant', tool_calls:[{ id:'a', function:{ name:'shell', arguments:'{}' } }] });
messages.push({ role:'tool', tool_call_id:'a', content:'x'.repeat(24000) + '\nERROR: compilation failed; exit 1' });
const after = estimateAgentPrompt(messages, [{ name:'shell', description:'Run a command' }]);
assert.ok(after > before + 6000, 'New output and tool definitions count before dispatch');
assert.ok(after > agentInputLimit(8192, 4096), 'Compact before consuming output reserve');
assert.equal(agentInputLimit(null), Infinity);
assert.ok(agentInputLimit(2048, 4096) > 0);
assert.equal(calibratedPromptEstimate(3000, 1000, 2000), 6000);
assert.equal(calibratedPromptEstimate(3000, 1000, 500), 3000);
const recent = { role:'tool', tool_call_id:'b', content:'y'.repeat(2000) };
messages.push(recent);
trimAgentToolHistory(messages, 1);
assert.match(messages[2].content, /ERROR: compilation failed; exit 1$/);
assert.equal(messages[2].tool_call_id, 'a');
assert.equal(messages[3], recent);
assert.ok(messages[2].content.length < 1400);
console.log('Agent context: growth, answer reserve, usage calibration, and error-tail preservation passed');
