import assert from 'node:assert/strict';
import { activeChatJobCount, hasActiveJob, createLiveJob, broadcast, attachListener, finishLiveJob, stopLiveJob, waitForStoppingJob } from '../src/liveJobs.js';

const job = createLiveJob(991, 1);
assert.equal(activeChatJobCount(), 1, 'deploys see server-owned chat work');
assert.match(job.id, /^[0-9a-f-]{36}$/);
broadcast(job, { type: 'user_msg', msg: { id: 42, role: 'user', content: 'Build a pond' } });
broadcast(job, { type: 'context', used: 1000, budget: 32768, estimated: true });
broadcast(job, { type: 'tok_s', n: 100, value: 20, promptN: 1200 });
assert.deepEqual(job.state.context, { used: 1300, budget: 32768, estimated: false });
broadcast(job, { type: 'delta', text: 'Work in progress' });
assert.equal(job.state.phase, 'reply');
broadcast(job, { type: 'thinking', text: 'Next round' });
assert.equal(job.state.phase, 'thinking', 'old reply text cannot hide current reasoning after reconnect');
broadcast(job, { type: 'error', message: 'connection interrupted' });
assert.equal(job.state.text, 'Work in progress');
broadcast(job, { type: 'agent_start', run: { id: 7, workspace_id: 4 }, workspace: { id: 4, name: 'game' } });
const received = [];
const detach = attachListener(job, ev => received.push(ev));
assert.equal(received[0].context.used, 1300);
assert.equal(received[0].promptN, 1200);
assert.equal(received[0].text, 'Work in progress');
assert.equal(received[0].phase, 'thinking');
assert.equal(received[0].workspace.id, 4, 'reattach restores a workspace created after the browser loaded');
assert.equal(received[0].userMsg.id, 42, 'a prompt saved before the viewer attached is replayed');
assert.equal(received[0].jobId, job.id, 'the viewer can identify the turn it is watching');
detach();
assert.equal(job.abort.signal.aborted, false, 'detaching a viewer does not cancel the server job');
broadcast(job, { type: 'context', used: 2200, budget: 32768 });
broadcast(job, { type: 'tok_s', n: 50, value: 25 });
assert.equal(job.state.context.used, 2250, 'new round starts from its own prompt');
assert.equal(job.state.context.budget, 32768, 'context limit is unchanged');
console.log('Live-job context and interrupted-work recovery checks passed.');

broadcast(job, { type: 'tok_s', n: 80, promptN: 2200, estimated: true });
assert.equal(job.state.context.estimated, true, 'estimated streaming counts remain labeled on resume');
broadcast(job, { type: 'tool_delta', index: 0, name: 'web_search', args: '{"query":"ducks"}' });
broadcast(job, { type: 'reset_text' });
assert.equal(job.state.text, '', 'new rounds have authoritative empty text');
assert.equal(job.state.liveTool, null, 'completed tool arguments cannot leak into the next round');
broadcast(job, { type: 'tool_delta', index: 0, name: 'web_search', args: '{"query":"ponds"}' });
assert.equal(job.state.liveTool.args, '{"query":"ponds"}', 'same-index tool calls start a fresh argument buffer');

broadcast(job, { type: 'image_job', prompt: 'A duck' });
broadcast(job, { type: 'image_progress', phase: 'denoising', step: 4, steps: 8, image: 2, n: 2, etaSeconds: 9 });
assert.equal(job.state.image.etaSeconds, 9, 'image ETA remains available after reconnect');
assert.equal(job.state.image.image, 2);

broadcast(job, { type: 'done', msg: { id: 43, role: 'assistant', content: 'Done' } });
assert.equal(job.status, 'done', 'viewers see a delivered reply immediately');
assert.equal(hasActiveJob(991), true, 'delivery does not settle the worker');
assert.equal(activeChatJobCount(), 1, 'deployment still waits for post-delivery work');
assert.throws(() => createLiveJob(991, 1), /already generating/, 'another reply cannot race post-delivery cleanup');
assert.equal(await waitForStoppingJob(991, 1), false, 'a delivered but unsettled worker keeps its slot');
finishLiveJob(job);
assert.equal(hasActiveJob(991), false);
assert.equal(activeChatJobCount(), 0);
const finished = [];
attachListener(job, (event) => finished.push(event));
assert.equal(finished[0].status, 'done');
assert.equal(finished[0].finalMsg.id, 43, 'late viewers receive the saved final reply');

const stopped = createLiveJob(992, 1);
broadcast(stopped, { type: 'done', outcome: 'stopped', msg: { id: 44, content: 'partial' } });
const partial = [];
attachListener(stopped, ev => partial.push(ev));
assert.equal(partial[0].outcome, 'stopped', 'a saved partial keeps its outcome on reconnect');
assert.equal(stopLiveJob(992, 2), false, 'other users cannot stop a job');
assert.equal(stopLiveJob(992, 1), true);
assert.equal(stopped.abort.signal.aborted, true);
assert.equal(activeChatJobCount(), 1, 'stopping still counts as active until cleanup finishes');
assert.throws(() => createLiveJob(992, 1), /already generating/, 'a new turn waits for old cleanup');
const retry = waitForStoppingJob(992, 500);
setTimeout(() => finishLiveJob(stopped, 'stopped'), 10);
assert.equal(await retry, true, 'an immediate retry waits for cleanup to settle');
assert.equal(activeChatJobCount(), 0);
assert.equal(createLiveJob(992, 1).status, 'running', 'a new turn starts after cleanup');
