import assert from 'node:assert/strict';
import { prepareMediaGpu } from '../src/mediaGpu.js';
const GiB = 1024 ** 3;
const models = {default_model:'qwen',models:[{id:'qwen',task:'image',kind:'diffusers',device:'cuda'}]};
let free = 1, calls = [], progress = [];
const opts = {models,requested:'auto',task:'image',memory:async()=>({totalBytes:16*GiB,usedBytes:(16-free)*GiB}),list:async()=>[{id:'busy',status:'loaded'},{id:'idle',status:'loaded'},{id:'untouched',status:'loaded'}],reclaim:async id=>{calls.push(id);if(id==='busy')return false;free=8;return true;},onProgress:p=>progress.push(p.phase)};
assert.deepEqual(await prepareMediaGpu(opts),['idle']);
assert.deepEqual(calls,['busy','idle']);
assert.ok(progress.includes('freeing_memory'));
calls=[];
assert.deepEqual(await prepareMediaGpu(opts),[]);
assert.deepEqual(calls,[]);
free=1;
await prepareMediaGpu({...opts,models:{...models,models:[{...models.models[0],device:'cpu'}]}});
assert.deepEqual(calls,[]);
await prepareMediaGpu({...opts,memory:async()=>null});
assert.deepEqual(calls,[]);
const abort = new AbortController();abort.abort();
await assert.rejects(prepareMediaGpu({...opts,signal:abort.signal}),{name:'AbortError'});
console.log('Media GPU: idle reclaim, active refusal, capacity stop, CPU bypass, missing telemetry, cancellation passed');
