import assert from 'node:assert/strict';
import { trackStreamProgress } from '../src/streamProgress.js';
let now = 0;
const events = [];
const report = trackStreamProgress((text, meta) => events.push({text, meta}), { messages:[{role:'user',content:'Build a game'}], now:()=>now });
report('', {reasoning:'Thinking about a game'});
const first = events.at(-1).meta.timings;
assert(first.prompt_n > 0 && first.predicted_n > 0 && first.estimated);
now = 600;
report('', {toolFrag:{args:'{"content":"<html>updated game</html>"}'}});
assert(events.at(-1).meta.timings.predicted_n > first.predicted_n, 'tool arguments grow the live meter');
report.finish({prompt_tokens:1000,completion_tokens:300});
assert.deepEqual(events.at(-1).meta.timings, {prompt_n:1000,predicted_n:300,predicted_per_second:null,estimated:false});
const next = [];
trackStreamProgress((_,m)=>next.push(m), {messages:[],now:()=>now})('new');
assert(next[0].timings.predicted_n < first.predicted_n, 'each model request resets output accounting');
const local=[];
const native=trackStreamProgress((_,m)=>local.push(m), {now:()=>now});
native('',{timings:{prompt_n:800,predicted_n:45,predicted_per_second:30}});
assert.equal(local[0].timings.predicted_per_second,30,'native telemetry stays authoritative');
console.log('Streaming context telemetry checks passed (no inference).');
