// Diffusion LLMs (LLaDA / Dream / diffusion-gemma): text is generated by
// iteratively denoising a fully-masked canvas — not autoregressive. These
// models can't run through the normal llama-server router at all, so chat.js
// detects them and drives llama-diffusion-cli here instead, forwarding every
// intermediate frame so the UI shows the answer literally taking shape.
//
// This module is deliberately binary/model-agnostic (see notes/BUILD-DIFFUSION-
// GEMMA.md): the CLI path, model dir, flag preset and pty behaviour are all
// env-configurable, so once a diffusion-gemma-capable binary is built it drops
// in with no code change.
import { spawn } from 'node:child_process';
import { existsSync, readdirSync, statSync } from 'node:fs';
import { basename, dirname, join } from 'node:path';
import { listModels, unloadModel } from './llama.js';

const BIN = process.env.DIFFUSION_CLI
  ?? '/home/cranky/bin/llama-prebuilt/b9966-vulkan/llama-diffusion-cli';
const MODELS_DIR = process.env.DIFFUSION_MODELS_DIR
  ?? '/home/lewis/llm-models/llama.cpp-models/diffusion';
// LLaDA/Dream flag preset works on the current b9966 binary; the diffusion-gemma
// EB decoder needs different flags — set DIFFUSION_MODE=gemma once its binary
// exists (or override entirely with DIFFUSION_EXTRA_ARGS="--foo bar --baz").
const MODE = process.env.DIFFUSION_MODE ?? 'llada';
// --diffusion-visual may need a real pty to emit progressive frames on some
// builds. If frames don't stream, set DIFFUSION_PTY=1 to wrap the spawn in
// `script -qec` (see the smoke test in the build note).
const USE_PTY = process.env.DIFFUSION_PTY === '1';
const MAX_RUN_MS = Number(process.env.DIFFUSION_MAX_MS ?? 10 * 60 * 1000);

// one GPU → one denoising job at a time (guards against a second user starting
// a run while a diffusion CLI already owns the VRAM)
let busy = false;
export const diffusionBusy = () => busy;

// eslint-disable-next-line no-control-regex
const ANSI = /\x1b\[[0-9;?]*[A-Za-z]|\x1b[c=>]|\r/g;

// The diffusion-gemma CLI's harmony-style chat template puts its scratchpad
// in a <|channel>thought ... <channel|> block before the real answer, and
// (in -cnv/conversation mode) appends its own perf-stats trailer + a bare
// "> " REPL prompt after the answer. None of that belongs in the saved
// message — strip down to just the final answer text.
function extractFinalAnswer(raw) {
  let t = String(raw ?? '');
  const lastChan = t.lastIndexOf('<channel|>');
  if (lastChan !== -1) t = t.slice(lastChan + '<channel|>'.length);
  t = t.split(/\n\s*total time:/)[0];
  t = t.replace(/^\s*>\s*$/gm, '');
  return t.trim();
}
// LLaDA/Dream (old b9966 binary) repaint with a full clear (\x1b[2J or
// \x1b[H\x1b[J). The diffusion-gemma EB decoder (PR #24423,
// llama-diffusion-cli) instead uses the terminal "synchronized output" idiom:
// each redraw is bracketed by \x1b[?2026l\x1b[?2026h (end/begin a sync batch)
// immediately followed by a cursor-up + carriage-return to overwrite the
// canvas in place — there's no full-screen clear at all. Match both so the
// same parser handles either binary.
const CLEAR = /\x1b\[2J|\x1b\[H\x1b\[J|\x1b\[3J|\x1b\[\?2026l\x1b\[\?2026h\x1b\[\d+A\r/;

// A router model id (or a bare gguf name) is a diffusion model if its name
// matches the family markers or it's explicitly listed in DIFFUSION_MODEL_IDS.
const EXPLICIT = new Set(
  (process.env.DIFFUSION_MODEL_IDS ?? '').split(',').map((s) => s.trim().toLowerCase()).filter(Boolean),
);
const MARKER = /diffusion|llada|dream|dllm/i;
export function isDiffusionModel(id) {
  if (!id) return false;
  return EXPLICIT.has(String(id).toLowerCase()) || MARKER.test(String(id));
}

// The real gguf path. Preferred source: the model's own router registration
// args (`--model <path>` / `-m <path>`), so a diffusion gguf sitting anywhere
// in the normal model area still resolves. Falls back to a scan of MODELS_DIR.
export function diffusionModelFile(routerArgs, id) {
  if (Array.isArray(routerArgs)) {
    const i = routerArgs.indexOf('--model');
    const j = routerArgs.indexOf('-m');
    const k = i >= 0 ? i : j;
    if (k >= 0 && routerArgs[k + 1] && existsSync(routerArgs[k + 1])) return routerArgs[k + 1];
  }
  if (existsSync(MODELS_DIR)) {
    const hit = readdirSync(MODELS_DIR)
      .filter((f) => f.endsWith('.gguf'))
      .find((f) => f.replace(/\.gguf$/, '').toLowerCase() === String(id ?? '').toLowerCase());
    if (hit) return join(MODELS_DIR, hit);
  }
  return null;
}

// Any loose diffusion ggufs in the dedicated dir that AREN'T already router-
// registered — merged into the model list so they show in the picker too.
export function listLooseDiffusionModels(knownIds = new Set()) {
  if (!existsSync(MODELS_DIR)) return [];
  return readdirSync(MODELS_DIR)
    .filter((f) => f.endsWith('.gguf'))
    .map((f) => ({ id: f.replace(/\.gguf$/, ''), file: join(MODELS_DIR, f), size: statSync(join(MODELS_DIR, f)).size }))
    .filter((m) => !knownIds.has(m.id));
}

export const diffusionAvailable = () => existsSync(BIN);

function buildArgs({ modelFile, prompt, systemPrompt, tokens, steps }) {
  if (process.env.DIFFUSION_EXTRA_ARGS) {
    // fully manual override — user supplies everything after -m/-p/-n
    const base = ['-m', modelFile, '-p', prompt, '-n', String(tokens)];
    if (systemPrompt) base.push('-sys', systemPrompt);
    return [...base, ...process.env.DIFFUSION_EXTRA_ARGS.split(/\s+/).filter(Boolean)];
  }
  const args = ['-m', modelFile, '-p', prompt, '-n', String(tokens)];
  if (systemPrompt) args.push('-sys', systemPrompt);
  if (MODE === 'gemma') {
    // Entropy-Bound decoder (PR #24423). Flag names confirmed loosely from the
    // PR; adjust here once the real binary's --help is known.
    args.push('-cnv', '--diffusion-visual', '--diffusion-eb-max-steps', String(steps));
  } else {
    // LLaDA / Dream (works on b9966)
    args.push('--diffusion-visual', '--diffusion-steps', String(steps), '--diffusion-algorithm', '4', '--temp', '0');
  }
  args.push('-ngl', String(process.env.DIFFUSION_NGL ?? '20'));
  return args;
}

// Run one denoising pass. onFrame({ n, steps, text }) fires per visual frame
// (throttled ~8fps, newest frame never dropped). Returns { text, ms, stopped }.
export async function generateDiffusion({
  modelFile, prompt, systemPrompt = '', tokens = 128, steps = 64, onFrame, signal, log,
}) {
  if (!existsSync(BIN)) throw new Error(`diffusion binary not found at ${BIN} — see notes/BUILD-DIFFUSION-GEMMA.md`);
  if (!modelFile || !existsSync(modelFile)) throw new Error('diffusion model file not found');
  if (busy) throw new Error('a diffusion run is already in progress — one GPU, one denoiser at a time');
  busy = true;

  const nSteps = Math.min(Math.max(Number(steps) || 64, 8), 512);
  const nTokens = Math.min(Math.max(Number(tokens) || 128, 16), 1024);
  const t0 = Date.now();
  let child = null;
  let killed = false;
  try {
    // the denoiser needs the VRAM the chat models are holding
    const loaded = (await listModels().catch(() => [])).filter((m) => m.status === 'loaded' || m.status === 'sleeping');
    for (const m of loaded) {
      onFrame?.({ n: 0, steps: nSteps, text: `freeing VRAM (unloading ${m.id})…`, phase: 'load' });
      await unloadModel(m.id).catch(() => {});
    }
    onFrame?.({ n: 0, steps: nSteps, text: 'loading the diffusion model…', phase: 'load' });

    const argv = buildArgs({
      modelFile, prompt: String(prompt).slice(0, 6000), systemPrompt: systemPrompt.slice(0, 4000),
      tokens: nTokens, steps: nSteps,
    });
    // from-source builds (diffusion-gemma) link their ggml/llama .so's
    // alongside the binary rather than baking everything in statically like
    // the old official release builds did — point the loader at BIN's own
    // directory so the deployed copy works even if the build tree is gone.
    const spawnEnv = { ...process.env, LD_LIBRARY_PATH: [dirname(BIN), process.env.LD_LIBRARY_PATH].filter(Boolean).join(':') };
    if (USE_PTY) {
      // wrap in `script` so the CLI believes it has a tty
      const inner = [BIN, ...argv].map((a) => `'${String(a).replace(/'/g, `'\\''`)}'`).join(' ');
      child = spawn('script', ['-qec', inner, '/dev/null'], { stdio: ['ignore', 'pipe', 'pipe'], env: spawnEnv });
    } else {
      child = spawn(BIN, argv, { stdio: ['ignore', 'pipe', 'pipe'], env: spawnEnv });
    }
    log?.info({ bin: BIN, mode: MODE, pty: USE_PTY }, 'diffusion run started');

    const killTimer = setTimeout(() => { killed = true; child.kill('SIGKILL'); }, MAX_RUN_MS);
    const onAbort = () => { if (child.exitCode === null) { killed = true; child.kill('SIGKILL'); } };
    signal?.addEventListener('abort', onAbort, { once: true });

    // --diffusion-visual repaints the whole current canvas each step, separated
    // by terminal-clear escapes. Frames arrive faster than a human can read —
    // throttle to ~8fps but never drop the newest frame.
    let buf = '';
    let frame = '';
    let step = 0;
    let lastSent = 0;
    let trailer = null;
    const emit = (text) => {
      step += 1;
      frame = text;
      const now = Date.now();
      if (now - lastSent >= 120) {
        lastSent = now;
        clearTimeout(trailer); trailer = null;
        onFrame?.({ n: step, steps: nSteps, text, phase: 'step' });
      } else if (!trailer) {
        trailer = setTimeout(() => {
          trailer = null; lastSent = Date.now();
          onFrame?.({ n: step, steps: nSteps, text: frame, phase: 'step' });
        }, 130);
      }
    };
    child.stdout.on('data', (d) => {
      buf += d.toString('utf8');
      const parts = buf.split(CLEAR);
      if (parts.length > 1) {
        for (const p of parts.slice(0, -1)) {
          const text = p.replace(ANSI, '');
          if (text.trim()) emit(text);
        }
        buf = parts[parts.length - 1];
      }
    });
    let errTail = '';
    child.stderr.on('data', (d) => { errTail = (errTail + d.toString('utf8')).slice(-4000); });

    const code = await new Promise((res) => child.on('close', res));
    clearTimeout(killTimer);
    clearTimeout(trailer);
    signal?.removeEventListener('abort', onAbort);

    const rawFinal = (buf.replace(ANSI, '').trim() || frame.trim());
    const final = extractFinalAnswer(rawFinal);
    if (killed) return { text: final, stopped: true, ms: Date.now() - t0 };
    if (code !== 0 && !final) {
      const lastErr = errTail.split('\n').filter(Boolean).pop() ?? '';
      throw new Error(`diffusion run failed (exit ${code}): ${lastErr}`);
    }
    return { text: final, ms: Date.now() - t0 };
  } finally {
    busy = false;
    if (child && child.exitCode === null) { try { child.kill('SIGKILL'); } catch { /* gone */ } }
  }
}
