import assert from 'node:assert/strict';
import { workspaceState } from '../src/lib/workspaceState.js';
const values = new Map();
const storage = { getItem: key => values.get(key), setItem: (key, value) => values.set(key, value) };
const first = workspaceState(storage, 1);
first.saveDraft(10, 'chat draft'); first.saveDraft(20, 'agent draft');
first.select('chat', 10); first.select('agent', 20);
const restored = workspaceState(storage, 1);
assert.equal(restored.draft(10), 'chat draft');
assert.equal(restored.draft(20), 'agent draft');
assert.equal(restored.selected('agent'), 20);
assert.equal(restored.selected('chat'), 10);
assert.equal(workspaceState(storage, 2).draft(10), '');
restored.saveDraft(10, '');
assert.equal(workspaceState(storage, 1).draft(10), '');
values.set('dp_workspace_v1:3', 'null');
assert.equal(workspaceState(storage, 3).draft(10), '');
first.saveDraft(30, 'newer store write');
restored.saveDraft(20, 'older handle write');
assert.equal(workspaceState(storage, 1).draft(30), 'newer store write');
console.log('Workspace draft and selection isolation passed.');
