<script>
  // Diffusion LLM lab: text generated by denoising a masked sequence — the
  // whole reply materializes at once instead of streaming left-to-right.
  // Frames arrive over SSE from llama-diffusion-cli --diffusion-visual.
  import Duck from './Duck.svelte';
  import Sparkles from '@lucide/svelte/icons/sparkles';
  import Square from '@lucide/svelte/icons/square';
  import { toast } from '../lib/toast.svelte.js';
  import { lab, loadDiffusionModels, runDiffusion } from '../lib/diffusion.svelte.js';

  let prompt = $state('');
  let model = $state('');
  let tokens = $state(96);
  let steps = $state(64);
  let temp = $state(0);
  let algorithm = $state(4);

  $effect(() => { loadDiffusionModels(); });
  $effect(() => { if (!model && lab.models.length) model = lab.models[0].id; });

  const run = $derived(lab.run);
  const running = $derived(run && !run.finished);

  const ALGOS = [
    { v: 4, label: 'confidence (default)' },
    { v: 0, label: 'origin' },
    { v: 1, label: 'entropy' },
    { v: 2, label: 'margin' },
    { v: 3, label: 'random' },
  ];

  function go() {
    if (!prompt.trim() || running || !model) return;
    runDiffusion({
      model, prompt: prompt.trim(),
      tokens: Number(tokens), steps: Number(steps),
      temp: Number(temp), algorithm: Number(algorithm),
    })?.catch((e) => toast(e.message, 'error'));
  }

  function keydown(e) {
    if (e.key === 'Enter' && (e.ctrlKey || e.metaKey)) { e.preventDefault(); go(); }
  }
</script>

<div class="dlab">
  <aside class="form">
    <p class="blurb">
      Diffusion LLMs don't write left to right — they start from a fully
      masked reply and denoise it over many steps, so you watch the whole
      text take shape at once.
    </p>
    <label class="lbl" for="dl-model">Model</label>
    <select id="dl-model" bind:value={model}>
      {#each lab.models as m (m.id)}
        <option value={m.id}>{m.id} ({(m.size / 1e9).toFixed(1)} GB)</option>
      {/each}
    </select>
    <label class="lbl" for="dl-prompt">Prompt</label>
    <textarea id="dl-prompt" rows="5" bind:value={prompt} onkeydown={keydown}
      placeholder="Explain why the sky is blue in two sentences."></textarea>
    <div class="row">
      <div class="field">
        <label class="lbl" for="dl-tokens">Tokens · {tokens}</label>
        <input id="dl-tokens" type="range" min="16" max="512" step="16" bind:value={tokens} />
      </div>
    </div>
    <div class="row">
      <div class="field">
        <label class="lbl" for="dl-steps">Steps · {steps}</label>
        <input id="dl-steps" type="range" min="8" max="256" step="8" bind:value={steps} />
      </div>
    </div>
    <div class="row">
      <div class="field">
        <label class="lbl" for="dl-temp">Temp</label>
        <input id="dl-temp" type="number" min="0" max="2" step="0.1" bind:value={temp} />
      </div>
      <div class="field">
        <label class="lbl" for="dl-algo">Algorithm</label>
        <select id="dl-algo" bind:value={algorithm}>
          {#each ALGOS as a (a.v)}<option value={a.v}>{a.label}</option>{/each}
        </select>
      </div>
    </div>
    {#if running}
      <button class="gen stop" onclick={() => run.abort?.()}>
        <Square size={13} /> Stop
      </button>
    {:else}
      <button class="gen" onclick={go} disabled={!prompt.trim() || !model || lab.available === false}>
        <Sparkles size={14} /> Denoise
      </button>
    {/if}
    {#if lab.available === false}
      <div class="offline">No diffusion models installed on this box.</div>
    {/if}
  </aside>

  <section class="main">
    {#if run}
      <div class="runhead">
        {#if run.phase === 'load'}
          <span class="shimmertext">{run.loadText}</span>
        {:else if run.phase === 'denoise'}
          <span class="mono">step {run.step}/{run.steps}</span>
        {:else if run.phase === 'done'}
          <span class="mono ok">done in {(run.ms / 1000).toFixed(1)}s</span>
        {:else if run.phase === 'error'}
          <span class="mono bad">failed</span>
        {/if}
        {#if run.phase === 'denoise' || run.phase === 'done'}
          <div class="bar"><div class="fill" style:width="{Math.min(100, Math.round((run.step / (run.steps || 1)) * 100))}%"></div></div>
        {/if}
      </div>
      {#if run.error}
        <div class="err">{run.error}</div>
      {:else}
        <pre class="canvas" class:settled={run.phase === 'done'}>{run.text || ' '}</pre>
      {/if}
    {:else}
      <div class="idle">
        <Duck mood="think" px={4} />
        <p>Pick a model, write a prompt, and watch the reply denoise into place.</p>
      </div>
    {/if}
  </section>
</div>

<style>
  .dlab { flex: 1; display: flex; min-height: 0; }
  .form {
    width: 290px; flex-shrink: 0; padding: 16px;
    border-right: 1px solid var(--border-soft); overflow-y: auto;
    display: flex; flex-direction: column; gap: 10px;
  }
  .blurb { margin: 0 0 4px; font-size: 12px; line-height: 1.55; color: var(--text-faint); }
  .lbl {
    font-size: 10.5px; font-weight: 600; letter-spacing: 0.07em;
    text-transform: uppercase; color: var(--text-faint);
  }
  textarea, select, input[type="number"] {
    width: 100%; box-sizing: border-box; resize: vertical;
    background: var(--bg-raised); color: var(--text);
    border: 1px solid var(--border-soft); border-radius: 9px;
    padding: 8px 10px; font-size: 13px; font-family: inherit;
  }
  textarea:focus, select:focus, input:focus { outline: none; border-color: var(--accent); }
  input[type="range"] { width: 100%; accent-color: var(--accent); }
  .row { display: flex; gap: 8px; }
  .field { flex: 1; min-width: 0; display: flex; flex-direction: column; gap: 4px; }
  .gen {
    all: unset; cursor: pointer; display: flex; align-items: center; justify-content: center;
    gap: 7px; padding: 10px; border-radius: 10px; font-size: 13px; font-weight: 600;
    background: var(--accent); color: #1a1408;
  }
  .gen:hover:not(:disabled) { filter: brightness(1.08); }
  .gen:disabled { opacity: 0.5; cursor: default; }
  .gen.stop { background: var(--bg-raised); color: var(--red); border: 1px solid var(--border-soft); }
  .offline { font-size: 12px; color: var(--red); }

  .main { flex: 1; min-width: 0; overflow-y: auto; padding: 20px 24px; display: flex; flex-direction: column; gap: 12px; }
  .idle {
    flex: 1; display: flex; flex-direction: column; align-items: center; justify-content: center;
    gap: 14px; color: var(--text-faint); font-size: 13.5px;
  }
  .runhead { display: flex; align-items: center; gap: 12px; }
  .mono { font-family: var(--mono); font-size: 12px; color: var(--text-dim); }
  .mono.ok { color: var(--green); }
  .mono.bad { color: var(--red); }
  .shimmertext {
    font-size: 12.5px; color: var(--text-dim);
    animation: dl-pulse 1.4s ease infinite;
  }
  @keyframes dl-pulse { 50% { opacity: 0.4; } }
  .bar { flex: 1; max-width: 260px; height: 4px; border-radius: 999px; background: var(--bg-raised); overflow: hidden; }
  .fill { height: 100%; background: var(--accent); border-radius: 999px; transition: width 200ms ease; }
  .canvas {
    margin: 0; padding: 16px 18px;
    background: var(--bg-card, var(--bg-raised)); border: 1px solid var(--border-soft);
    border-radius: 12px; font-family: var(--mono); font-size: 13px; line-height: 1.7;
    white-space: pre-wrap; word-break: break-word; color: var(--text-dim);
    min-height: 160px; transition: color 300ms ease;
  }
  .canvas.settled { color: var(--text); }
  .err {
    border: 1px solid color-mix(in srgb, var(--red) 35%, transparent);
    background: color-mix(in srgb, var(--red) 8%, transparent);
    color: var(--red); border-radius: 10px; padding: 10px 14px; font-size: 13px;
  }
</style>
